### PR TITLE
We want Japanese Desserts not Deserts

### PR DESCRIPTION
**Pull request by zoidbergwill**
No sand, more pom pom purin

## Which problem is this PR solving?
- A typo

## Short description of the changes
- Fixing a typo

### CODE REVIEW

**Comment by jpkrohling** [comment]
This got to be the best PR ever. Thanks for your contribution (and laugh)!

**Comment by jpkrohling** [comment]
Could you please sign off your commit, so that the DCO check passes? The details can be found here:
https://github.com/jaegertracing/jaeger/pull/1793/checks?check_run_id=218699400

**Comment by zoidbergwill** [comment]
Thanks for the quick review and approval. Sorry about the missed DCO. It's because I created the commits in the GitHub Web UI. Fixing now.

**Comment by kuhsinyv** [comment]
😅

**Pull request merged**
