### PR TITLE
Auto-generate gogo annotations for api_v3

### PR DESCRIPTION
**Pull request by yurishkuro**
## Which problem is this PR solving?
- Part of #4150

## Description of the changes
- Upgrade to new IDL that removes gogo annotation from api_v3/query.proto
- Add a pre-processor to inject annotations during build
- Fix tests
- Add start/end time to GetTrace test (which was failing in #6228)

## How was this change tested?
- 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by rim99** [comment]
Test this change in this draft PR: https://github.com/jaegertracing/jaeger/pull/6237
---
Moving gogoproto related lines out is a great idea, since original proto file could be used by other programming languages

**Comment by yurishkuro** [comment]
@rim99 please approve this change and I will merge it.

**Comment by rim99** [comment]
@yurishkuro woud you like to regenerate file `cmd/query/app/internal/api_v3/query_service.pb.go` after idl renaming `num_traces -> search_depth`? Or it will be handled by some automated flows?

Because to manage all test passed, I had to make this change:

https://github.com/jaegertracing/jaeger/pull/6237/commits/d6eeed8f8d36381a77e1c283fc419dafd32b8b06#diff-9f4e53eb6033f5e7d7af97a3fd7328e26bd3e5e948e01276cb85b3abfc0b2432

**Comment by rim99** [comment]
@yurishkuro woud you like to regenerate file `cmd/query/app/internal/api_v3/query_service.pb.go` after idl renaming `num_traces -> search_depth`? Or it will be handled by some automated flows?

Because to manage all test passed, I had to make this change:

https://github.com/jaegertracing/jaeger/pull/6237/commits/d6eeed8f8d36381a77e1c283fc419dafd32b8b06#diff-9f4e53eb6033f5e7d7af97a3fd7328e26bd3e5e948e01276cb85b3abfc0b2432

**Review by rim99 — APPROVED** [review]
NVM, I think that change might be related to my changes

**Review by mahadzaryab1 — APPROVED** [review]

**Pull request merged**
