### PR TITLE
Preparing release 1.1.0

### PR DESCRIPTION
**Pull request by yurishkuro**
Signed-off-by: Yuri Shkuro <ys@uber.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
Unblock https://github.com/istio/istio/issues/1792

**Comment by yurishkuro** [comment]
@tiffon please check if I missed anything important in the UI

**Comment by yurishkuro** [comment]
Found an issue https://github.com/jaegertracing/jaeger-ui/issues/149

**Comment by tiffon** [comment]
>@tiffon please check if I missed anything important in the UI

@yurishkuro Looks good :+1:

**Pull request merged**
