### PR TITLE
Fix unsorted imports

### PR DESCRIPTION
**Pull request by huynq0911**
## Which problem is this PR solving?
- Imports should be sorted by Go coding convention

## Short description of the changes
- Sort the imports

### CODE REVIEW

**Comment by pavolloffay** [comment]
@huynq0911 DCO failed. Please recmmit with `g commit -m "foo" -s`

**Comment by huynq0911** [comment]
> @huynq0911 DCO failed. Please recmmit with `g commit -m "foo" -s` -s flag

I have re-committed, please help me to check it again!

**Comment by huynq0911** [comment]
@pavolloffay: After resolving conflict, I saw some `Unknow field` and `Unresolved reference` error in line 107 and line 232-235. Seem the error occurred from the @black-adder PR ([Remove SASI indices](https://github.com/jaegertracing/jaeger/pull/1328)). Please help me to clarify it!

**Comment by pavolloffay** [comment]
@huynq0911 I had to merge a PR which caused conflict here. 

I am not sure why build is not failing due to incorrect order in master - might be better to look at that. Also please do not fix the order in auto-generated files.

**Comment by huynq0911** [comment]
> @huynq0911 I had to merge a PR which caused conflict here.
> 
> I am not sure why build is not failing due to incorrect order in master - might be better to look at that. Also please do not fix the order in auto-generated files.

Okay, I will fix that right now!

**Pull request merged**
