### PR TITLE
Automatically set GOMAXPROCS

### PR DESCRIPTION
**Pull request by rubenvp8510**
## Which problem is this PR solving?
-  Fixes Issue https://github.com/jaegertracing/jaeger-operator/issues/396

## Short description of the changes
- This PR set the GOMXPROCS to an automatic valid depending of the containers limits.

Does we need to make this configurable? I mean enable/disable using flags? @pavolloffay @objectiser

### CODE REVIEW

**Comment by objectiser** [comment]
@yurishkuro This is probably one you should answer, especially as it is using the Uber `automaxprocs` package? Would you prefer it configurable or enabled all the time?

**Comment by pavolloffay** [comment]
@rubenvp8510 did you test it on k8s? Does it use resource requests or limits?

**Comment by yurishkuro** [comment]
@objectiser it makes sense, when we build collector internally we're also using this module to adjust GOMAXPROCS

**Comment by rubenvp8510** [comment]
@pavolloffay Yes I did some tests and the library uses limits if they are defined.

With:
```yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "2000m"
```
I got this: 

2019/05/24 17:28:19 maxprocs: Updating GOMAXPROCS=2: determined from CPU quota

@yurishkuro should I leave this as it is? Or should I add a flag to enable/disable this behaviour?

**Pull request merged**
