### PR TITLE
Increase grpc retry to 1000 in xdock

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/jaegertracing/jaeger/commit/d8ab6948c24ddd8d9b27a9bb6459fe40be1fe432#r32679636

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by objectiser** [comment]
Short term solution, as if still fails, it would take a long time to report - but useful to see if this makes things more stable.

**Comment by pavolloffay** [comment]
Yep this is our goal. 

The current configuration waits 1000*50ms with 10% jitter so around 5s -+10%.

**Comment by yurishkuro** [comment]
Restarting the build in https://github.com/jaegertracing/jaeger-client-java/pull/602

**Comment by yurishkuro** [comment]
The build still failed.

**Comment by pavolloffay** [comment]
This is unfortunate. We could go even higher to 10000.

Isn't there problem with the PR itself. It failed on 

```
 [endtoend] test_driver→ (services=java-https testdriver=test_driver) ⇒ Fail: could not retrieve traces from query service
```

**Comment by yurishkuro** [comment]
It's possible, I didn't have time to investigate. I just know that PRs in many client libs have been failing recently on crossdock.

**Comment by iori-yja** [comment]
I got the reason. I remembered that once I had trouble with nginx which caches the name resolve result forever by default, so I wrote a workaround.
My hypothesis is that:
1. jaeger-collector dies until the database comes up.
2. docker restarts collector and occasionally it changes the IP.
3. nginx caches old IP so it shows Bad Gateway.

I wrote:
1. loop over wget collector's healthcheck before nginx's start-up.
2. nginx exposes :8080 port plainly as healthcheck.
3. crossdock waits for nginx.

On one of my environments that tends to fail (my other environments tend to succeed) could build successfully for several times.
I will push it to see it works for Travis, but the change isn't related to my PR. Should I revert it after seeing the result?

**Comment by iori-yja** [comment]
timeout this time... :disappointed: 

https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/504687620

**Comment by yurishkuro** [comment]
>  Should I revert it after seeing the result?

@iori-yja what are you referring to?

**Comment by iori-yja** [comment]
@yurishkuro My mistake, this one was that https://travis-ci.org/jaegertracing/jaeger-client-java/jobs/505333040.

I increased the timeout and am retrying.

**Comment by iori-yja** [comment]
@yurishkuro This [commit](https://github.com/jaegertracing/jaeger-client-java/pull/602/commits/9479bb3cc8b5cb0364f8db19e202b012a57aa6f0) is intended to work around the behavior and a little redundant. If the same problem happens in other PRs in client libs, possibly fix it in jaeger repository should be better (adding wait_for in crossdock's docker-compose, for example).

**Comment by yurishkuro** [comment]
I think the Java PR may be at fault for the failure itself, e.g. a Go client PR was successful (https://github.com/jaegertracing/jaeger-client-go/pull/379).

**Comment by iori-yja** [comment]
OK, it's figured out. The fault is in my change.

**Pull request merged**
