### PR TITLE
Bump gocql version

### LINKED ISSUE #826: Update `gocql` dependency
As reported via #651 and #812, the `gocql` dependency needs to be bumped. This can be done by changing an entry on `glide.lock` and `glide.yaml`, plus changing `pkg/cassandra/config/config.go` to use `&tls.Config` instead of `tls.Config`.

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- Closes #826, #812 and #651

## Short description of the changes
- Bumped `gocql`

### CODE REVIEW

**Comment by jpkrohling** [comment]
@black-adder, would you be able to check if the metrics still look good after this update?

**Comment by black-adder** [comment]
sure, ill pin this version internally and get back to you

**Comment by yurishkuro** [comment]
@black-adder I will hold my breath till you do...

**Comment by black-adder** [comment]
image

We deployed the new driver around 12PM yesterday, most metrics seem to have trended down (except # go-routines but those are free anyway). We're going to keep it running over the weekend to make sure everything looks ok but I on preliminary glance, things look good.

**Pull request merged**
