### PR TITLE
Fix batchProcessor to set correct span format flags

### PR DESCRIPTION
**Pull request by k0zl**
## Which problem is this PR solving?

Recently I've noticed that collector sends wrong tags "format" and "transport" in metric `jaeger_collector_spans_received_total`. 

Root cause: when batchProcessor was extended to be called from OTLP Receiver, it was given SpanOptions parameter that could specify a different span format OTLP, vs. always setting Proto. But the processor was still using hardcoded Proto format when invoking the next processor.

## How was this change tested?
Added unit test

## Checklist
- [ x ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ x ] I have signed all commits
- [ - ] I have added unit tests for the new functionality (not needed)
- [ x ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by albertteoh — APPROVED** [review]
Thanks! Please [sign your commit](https://github.com/jaegertracing/jaeger/pull/4796/checks?check_run_id=17310162478).

**Comment by k0zl** [comment]
> Thanks! Please [sign your commit](https://github.com/jaegertracing/jaeger/pull/4796/checks?check_run_id=17310162478).

Yep, already did

**Comment by k0zl** [comment]
@albertteoh could you approve the required workflows please?

**Review by yurishkuro — CHANGES_REQUESTED** [review]
please add unit test that illustrates the issue

**Comment by k0zl** [comment]
Added unit test

**Comment by yurishkuro** [comment]
Sorry, I am still missing the use case. Can you elaborate on the problem?
  * What is the setup? I.e. how are you receiving spans?
  * How are the metrics looking today and what you expect them to look?

**Review by yurishkuro — DISMISSED** [review]

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks!

**Pull request merged**
