### PR TITLE
Use Go 1.11 in Travis

### PR DESCRIPTION
**Pull request by isaachier**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Two of the CI jobs failed, probably related to Travis connectivity, so, I restarted them. One failed again, in a different step and might be relevant to this PR:

```
Go fmt, license check, or import ordering failures, run 'make fmt'
./crossdock/services/tracehandler_test.go
./plugin/storage/cassandra/dependencystore/storage.go
./plugin/storage/cassandra/spanstore/writer_test.go
make: *** [lint] Error 1
```

**Comment by isaachier** [comment]
Oh ya that formatting changes need to be applied. Ill get to that asap.

**Comment by isaachier** [comment]
The tests need to be rerun.

**Comment by isaachier** [comment]
Thanks @black-adder. Go 1.11 has an issue in the race detector when calling `len` on a channel (https://github.com/golang/go/issues/27070). Sarama fails this test repeatedly. IDK how you got tests to run here.

**Comment by black-adder** [comment]
Gonna roll back until the fix is in

**Pull request merged**
