### PR TITLE
Enable Lint Rule:  line-length-limit

### PR DESCRIPTION
**Pull request by varshith257**
## Which problem is this PR solving?
- Part of #5506 

## Description of the changes
-  Refactored the files to fix the lint of line-length limit

## How was this change tested?
-  `make lint`

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by varshith257** [comment]
@yurishkuro I have used the `golines `  library to fix it with the following command:

`golines -m 80 -w .`

It has fixed most of it but still emits the lint errors for comments. Can comments also need fixes or add ignore?

**Comment by yurishkuro** [comment]
Sorry, but I am not going to review 519 files. There was a clear comment in the config that the default length is not acceptable to us.

**Comment by varshith257** [comment]
Okay, will divide into multiple PRS. What could be acceptable line length limit? I am thinking of 120

**Comment by yurishkuro** [comment]
> I am thinking of 120 which I have seen in a Google article on the recommended line length limit for Golang or any suggestions?

How many breaks would be detected with 120?

**Comment by varshith257** [comment]
Ok, I have made changes and here are about 80 and 120 lll changes in the codebase:

80 lll - 18k+ lines and 519 files changed 
120 lll -  2708 lines and 213 files changed

**Comment by yurishkuro** [comment]
213 files is still too many, not worth the effort.

**Comment by varshith257** [comment]
@yurishkuro For 150 there are 81 files changed

**Comment by yurishkuro** [comment]
still not worth it. I don't want to spend an hour reviewing such changes that provide little benefit. I usually try to fix long lines when making changes in the code, as a side effect.

**Comment by varshith257** [comment]
ok! Closing

**Pull request closed without merging**
