### PR TITLE
Remove v2 directory

### LINKED ISSUE #2969: Remove v2 directory
We decided yesterday during the community sync call that we want to remove the v2 directory entirely until the OpenTelemetry Collector reaches GA. The ground is too unstable at the moment to rely on it as the base for the Jaeger v2.

### PR DESCRIPTION
**Pull request by f1r3starter**
Signed-off-by: Andrii Filenko <andrey.filenko.official@gmail.com>

## Which problem is this PR solving?
- Resolves #2969 

## Short description of the changes
- Remove v2 directory
- Update dependabot.yml

### CODE REVIEW

**Review by jpkrohling — COMMENTED** [review]
Looks good, but there's an unrelated change to the jaeger-ui in it. Could you please revert it?

**Comment by jpkrohling** [comment]
The CI seems to be failing because of the unrelated UI changes.

**Comment by f1r3starter** [comment]
@jpkrohling Yeap, sorry for that, fixed

**Review by jpkrohling — DISMISSED** [review]

**Comment by jpkrohling** [comment]
Could you please check the DCO failure?

**Comment by f1r3starter** [comment]
@jpkrohling Fixed, can you please trigger tests ?

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
