### PR TITLE
Build binaries for Linux on IBM Z / s390x architecture

### PR DESCRIPTION
**Pull request by prankkelkar**
Signed-off-by: Prasanna Kelkar <Prasanna.Kelkar@ibm.com>

## Which problem is this PR solving?
-  PR not intended to resolve specific issue but As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.

## Short description of the changes
- Added s390x specific changes to skip usage of `RACE` flag as it is not supported on s390x architecture.
- Added type casting in `plugin/storage/badger/stats_linux.go` file to resolve `mismatched types int64 and uint32` issue on s390x platform.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Please, see #1973. There are two main problems:

1. the extra time required to perform a build. Instead of running the whole build in a new arch, only the fast unit-tests should be executed
1. what happens if there's a new problem in the future? Are you able to commit to support this when it needs maintenance? The current maintainers do not have the necessary bandwidth to support arches that aren't used by ourselves...

**Comment by prankkelkar** [comment]
> Please, see #1973. There are two main problems:
> 
> 1. the extra time required to perform a build. Instead of running the whole build in a new arch, only the fast unit-tests should be executed
> 2. what happens if there's a new problem in the future? Are you able to commit to support this when it needs maintenance? The current maintainers do not have the necessary bandwidth to support arches that aren't used by ourselves...

1. I have modified the changes as per you instructions to run only unit tests for s390x architecture.
2. We already build and maintain jaeger on s390x. Our build instructions are published [here](https://github.com/linux-on-ibm-z/docs/wiki/Building-Jaeger)

**Comment by yurishkuro** [comment]
We're currently not running any tests on Windows or MacOS platforms, we only build the binaries for them. Could we do the same for this arch? This would have minimal impact on the CI time.

**Comment by prankkelkar** [comment]
Yes. It will be great if we can have binaries released for s390x architecture which could be downloaded directly. I believe changes in Makefile to add target for s390x in `build-all-platforms` should be enough. Please let me know if any more changes are needed.

> We're currently not running any tests on Windows or MacOS platforms, we only build the binaries for them. Could we do the same for this arch? This would have minimal impact on the CI time.

**Comment by prankkelkar** [comment]
@yurishkuro Could you please guide me with the changes which are needed to release binaries for s390x ?

**Comment by yurishkuro** [comment]
Follow the path of `make build-all-platforms` in the Makefile.

**Comment by prankkelkar** [comment]
@yurishkuro While i was adding linux s390x support i came across the names of the binaries used. for eg. `collector/collector-$(GOOS)`
In the case of s390x as the os name is same i.e Linux, two binaries will be created with the same name as per current code. To resolve this issue I was planning to add $(GOARCH) only to s390x binary name to differentiate it from amd64 linux.
Is there any other naming conventions we have to follow?

**Comment by yurishkuro** [comment]
Could we manage that at the directory name level, and keep the file names as is?

We may also consider not using OS in the binary name, only in the directory.

cc @jpkrohling @pavolloffay @objectiser

**Comment by jpkrohling** [comment]
Minikube adds both to the binaries:

    minikube-linux-amd64
    minikube-windows-amd64.exe
    minikube-darwin-amd64

In our case, it would probably be too noisy, so, the idea of grouping them by OS makes sense.

**Comment by prankkelkar** [comment]
I have currently added following code to handle this scenario
```
.PHONY: build-binaries-s390x
build-binaries-s390x:
	GOOS=linux GOARCH=s390x $(MAKE) build-platform-binaries

.PHONY: build-agent
build-agent:
ifeq ($(GOARCH), s390x)
	CGO_ENABLED=0 installsuffix=cgo go build -o ./cmd/agent/agent-$(GOOS)-$(GOARCH) $(BUILD_INFO) ./cmd/agent/main.go
else
	CGO_ENABLED=0 installsuffix=cgo go build -o ./cmd/agent/agent-$(GOOS) $(BUILD_INFO) ./cmd/agent/main.go
endif
```
This will only change the name of the binary of s390x and rest will remain as it is.
I have also tweaked `./scripts/travis/package-deploy.sh` to handle this change. Should i go ahead to update PR with this approach?

**Comment by yurishkuro** [comment]
sgtm

**Comment by prankkelkar** [comment]
@yurishkuro I have updated the PR to cross compile and release the binaries. Please review the code and let me know if anything needs to be changed.

**Pull request merged**
