### PR TITLE
Added .nocover to otel mains

### PR DESCRIPTION
**Pull request by joe-elliott**
## Which problem is this PR solving?
- Removing code coverage calculations from otel mains

## Short description of the changes
- Added .nocover to all otel mains

### CODE REVIEW

**Comment by yurishkuro** [comment]
I don't think this is necessary. Go does not report coverage for packages that have no test files. This is why we have a CI check that makes sure all packages have _some_ `*_test.go` files, unless the package only contains main or has .nocover marker. You can find some packages with empty_test.go because of that check (usually interface-only packages that don't have testable code).

**Comment by yurishkuro** [comment]
Feels like we should document these practices somewhere, wanna take a stub at that?

**Comment by joe-elliott** [comment]
I added `.nocover` b/c the standard agent/collector/ingester mains all have it.  So I presumed it was being used there to prevent those folders from counting toward code coverage.  I'll admit I didn't dig too deep on it :)

> Feels like we should document these practices somewhere, wanna take a stub at that?

Yup, I'll try to get something together.

**Review by yurishkuro — APPROVED** [review]
you're right

**Pull request merged**
