### PR TITLE
feat: add goleak check

### PR DESCRIPTION
**Pull request by inosmeet**
## Which problem is this PR solving?
- Partial Fix for: #5006 

## Description of the changes
- Added goleak check in `./plugin/storage/integration/` directory.

## How was this change tested?
- `make lint` `make test`

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by inosmeet** [comment]
`lint-goleak` now passes for all packages.
cc @yurishkuro

**Comment by inosmeet** [comment]
These tests are failing due to unexpected goroutines found by Goleak. After looking into it for a while, I’m unsure how to move forward. Can you nudge me in the right direction?? @yurishkuro

**Comment by yurishkuro** [comment]
See https://github.com/jaegertracing/jaeger/pull/5468#issuecomment-2163872037

**Comment by yurishkuro** [comment]
closing for now, feel free to re-open once you have the actual fixes

**Pull request closed without merging**
