### PR TITLE
[refractor] Switch to enums for ES mappings

### LINKED ISSUE #6067: [hygiene] Use enum instead of a string
in plugin/storage/es/mappings/mapping.go the function `GetMapping` accepts a string argument and does pattern matching on it, as well as uses it for loading template files internal to the package. It's a poor design, we should instead use a numeric enum (which has private string() function to map to the file name).

### PR DESCRIPTION
**Pull request by Saumya40-codes**
## Which problem is this PR solving?
- Resolves #6067 
- Follows up #6068 

## Description of the changes
- Currently in `plugin/storage/es/mappings/mapping.go` we are using bare string inorder to for the file mapping. This PR refractors this approach to use enums instead of string

## How was this change tested?
- running `go test` in respective files/directories

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
> Patch coverage is 61.70213% with 18 lines in your changes missing coverage.

Can we improve test coverage for the new code?

**Comment by Saumya40-codes** [comment]
> > Patch coverage is 61.70213% with 18 lines in your changes missing coverage.
> 
> Can we improve test coverage for the new code?

Should we add tests for `MappingTypeFromString` function? I'm not seeing any other way to make it get into test coverages of `mapping_test`

**Comment by yurishkuro** [comment]
The codecov comment  https://github.com/jaegertracing/jaeger/pull/6091#issuecomment-2414481703 shows all missing coverage. Is there any reason not to test all gaps?

**Comment by Saumya40-codes** [comment]
We actually can, I just thought 

> The codecov comment [#6091 (comment)](https://github.com/jaegertracing/jaeger/pull/6091#issuecomment-2414481703) shows all missing coverage. Is there any reason not to test all gaps?

We were missing out on testing `MappingTypeFromString` part which is now covered 
I think it should be good now!

**Review by yurishkuro — APPROVED** [review]

**Comment by Saumya40-codes** [comment]
Anything else I'm missing on @yurishkuro ?

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
