### PR TITLE
Fix SPM clearn-all 

### PR DESCRIPTION
**Pull request by hellspawn679**
## Which problem is this PR solving?
- `make clean-all` was not working for `docker-compose/monitor/Makefile`

## Description of the changes
- update  `docker-compose/monitor/Makefile` clean-all

## How was this change tested?
- 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
what "wasn't working" specifically?

**Comment by hellspawn679** [comment]
> what "wasn't working" specifically?

image

**Comment by yurishkuro** [comment]
looks fine to me. If you don't have `latest` tags they obviously cannot be purged, but the command didn't fail.

**Comment by hellspawn679** [comment]
> looks fine to me. If you don't have `latest` tags they obviously cannot be purged, but the command didn't fail.

so we can add a make command like `clean-all-dev` to remove  docker images for when we use  `make dev `

**Comment by yurishkuro** [comment]
why do we need to add anything? The command works. Even when there is nothing to remove:
```
$ make clean-all
# Also cleans up intermediate cached containers.
docker system prune -f
Total reclaimed space: 0B
docker rmi -f jaegertracing/all-in-one:dev ; \
	docker rmi -f jaegertracing/all-in-one:latest ; \
	docker rmi -f otel/opentelemetry-collector-contrib:latest ; \
	docker rmi -f prom/prometheus:latest ; \
	docker rmi -f grafana/grafana:latest
Error response from daemon: No such image: jaegertracing/all-in-one:dev
Error response from daemon: No such image: jaegertracing/all-in-one:latest
Error response from daemon: No such image: otel/opentelemetry-collector-contrib:latest
Error response from daemon: No such image: prom/prometheus:latest
Error response from daemon: No such image: grafana/grafana:latest
```

**Pull request closed without merging**
