### PR TITLE
Allow the ILM policy name to be configurable

### PR DESCRIPTION
**Pull request by jrRibeiro**
## Which problem is this PR solving?

- Resolves https://github.com/jaegertracing/jaeger/issues/2967

## Short description of the changes

- Add an option `--ilm-policy-name` to `esmapping-generator`, to set the policy name in the mappings file;
- Set the mapping's option in the rollover script (using an env var - `ES_ILM_POLICY_NAME`).
- The policy name defaults to `jaeger-ilm-policy` (both in the mapping generator and in the `init` action of the rollover script), so no breaking changes are added.

### CODE REVIEW

**Review by yurishkuro — DISMISSED** [review]

**Comment by jrRibeiro** [comment]
> @jrRibeiro I am not sure our CI covers this part of ES maintenance, did you do some manual testing? If so could you post some test results / evidence?

Yes I did some manual testing but it's better to actually test the change as part of the integration tests of the index rollover.

I just added a new integration test (and refactored the tests a bit) to test both the default ILM policy name (to make sure that not setting the env var still works) and also a new test to set the env var and test if the ILM policy associated with the created indices matches the one we define.

**Review by yurishkuro — DISMISSED** [review]
LGTM 

@albertteoh can you take a look at the integration test changes?

**Review by albertteoh — DISMISSED** [review]
LGTM too.

**Review by albertteoh — APPROVED** [review]

**Comment by albertteoh** [comment]
Thanks @jrRibeiro!

**Comment by jrRibeiro** [comment]
> Thanks @jrRibeiro!

Thank you @yurishkuro and @albertteoh!

**Pull request merged**
