### PR TITLE
Use ES 7.x mappings when ES 6.8 detected

### PR DESCRIPTION
**Pull request by jan25**
## Which problem is this PR solving
- Resolves https://github.com/jaegertracing/jaeger-operator/issues/634
## Short description of the changes
- Mappings for ES7.x are compatible with ES6.8. This PR enforces ES7 mappings when ES >=6.8 version is detected

### CODE REVIEW

**Comment by pavolloffay** [comment]
Unfortunately, this will not work see https://github.com/jaegertracing/jaeger/issues/1858. 

We will also need an integration test to verify the behavior.

**Comment by jan25** [comment]
Oh. Thanks for linking that issue. I'll do more manual tests and setup a integration test

**Comment by pavolloffay** [comment]
This is not needed. ES7 indices can read indices created by ES6 by default.

**Comment by pavolloffay** [comment]
@jan25 thanks for looking into this!

**Pull request closed without merging**
