### PR TITLE
Update Go version to 1.20

### LINKED ISSUE #4202: [Feature]: Migrate to go 1.20
### Requirement

[Go 1.20 officially released today](https://tip.golang.org/doc/go1.20)
There's improvements on the garbage collector. It informs that its overall performace improves by up to 2% and reduces memory overheads. I guess that migrating to go 1.20 will provides improved performance, bug fixes, security enhancements and etc.

### Problem

There's no problem on Jaeger.
This proposal only include a simple suggestion.

Thanks.

### Proposal

Migrate to go runtime 1.20.

### Open questions

_No response_

### PR DESCRIPTION
**Pull request by SaarthakMaini**
## Which problem is this PR solving?
- Resolves #4202 

## Short description of the changes
All the files mentioned in issue #4202 have been updated with Go version 1.20 replacing version 1.19

Signed-off-by: Saarthak Maini <saarthakmainiofficial@gmail.com>

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]
Thanks! Please make sure that all commits (or squash into one) are signed per CONTRIBUTING.md

**Comment by SaarthakMaini** [comment]
I have signed the DCO as required!

Thank You Very Much for reviewing the changes

**Comment by albertteoh** [comment]
I think the unit test failures relate to golangci-lint incompatibility with go 1.20. We can try upgrading to [golangci-lint v1.51.0](https://github.com/golangci/golangci-lint/releases/tag/v1.51.0) in the Makefile [here](https://github.com/jaegertracing/jaeger/blob/main/Makefile#L396).

**Comment by yurishkuro** [comment]
Linter failing

Error: cmd/anonymizer/app/query/query.go:83:3: S1011: should replace loop with `spans = append(spans, received.Spans...)` (gosimple)

**Comment by SaarthakMaini** [comment]
Linter was failing due to check [S1011](https://github.com/dominikh/go-tools/blob/master/simple/doc.go#:~:text=%7D-,for%20i%20%3A%3D%20range%20y%20%7B,%7D,-for%20i%20%3A%3D%20range)

I have made the necessary changes

**Review by yurishkuro — APPROVED** [review]

**Comment by SaarthakMaini** [comment]
There was a merge conflict which was happening, so I pulled the latest changes from the main repo to my fork, then git pull (ed) the changes to the branch I'm working in locally, and then after merging the changes I pushed it again to Github

The previous update with merge conflict was giving Unit Test error and Kafka error

**Comment by SaarthakMaini** [comment]
The Unit Tests seem to be failing with exit code 2

What I have speculated is that:

* The problem might be in running and getting golangci-lint as the error is occurring at line 162 of Makefile
* We have to replace the `make` command with the `make all` command. [Reference](https://github.com/git-lfs/git-lfs/issues/3693#issuecomment-505473530)
* The error occurred is the following: 
`make: *** [Makefile:162: lint] Error 1`
`Error: Process completed with exit code 2.`
* I can also try undoing the version update I did to update golangci-lint to v1.51.0

Please let me know some suggestions and problems which I might be making for the same

Thank You!

**Comment by yurishkuro** [comment]
I see this error in the output
```
cmd/anonymizer/app/query/query.go:83: File is not `gofmt`-ed with `-s` (gofmt)
		spans = append(spans, received.Spans...) 
```

**Comment by yurishkuro** [comment]
try running `make fmt`

**Comment by SaarthakMaini** [comment]
I'm getting the following error on running `make fmt` in the jaegar folder:
make fmt
./scripts/import-order-cleanup.sh inplace
bash: C:\Users\saarthak: No such file or directory
make: *** [Makefile:153: fmt] Error 127

I came across this [article](https://stackoverflow.com/questions/69049182/file-is-not-gofmt-ed-with-s-why-is-this-happening-and-how-to-resolve-it) and am currently trying to solve it this way

Thank you for reviewing the changes and helping me along the way!

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks. I'm not going to merge it just yet, but for the next release.

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
