### PR TITLE
Fix failing kafka integration test

### PR DESCRIPTION
**Pull request by pavolloffay**
Supersedes #1066 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
The test seems to be stable. I have restarted it a couple of times.

**Comment by yurishkuro** [comment]
famous last words... :-)

**Comment by pavolloffay** [comment]
ouch the last restart failed

**Comment by pavolloffay** [comment]
It failed on RACE. It's a different error. I think  it could be merged as the original issue seems to be solved.
```bash
WARNING: DATA RACE
Write at 0x00c420364f2c by goroutine 27:
  internal/race.Write()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/sync/waitgroup.go:127 +0xf3
  github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Close()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:87 +0x11b
  github.com/jaegertracing/jaeger/plugin/storage/integration.(*KafkaIntegrationTestSuite).initialize.func2()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/integration/kafka_test.go:93 +0x41
  github.com/jaegertracing/jaeger/plugin/storage/integration.(*StorageIntegration).cleanUp()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/integration/integration_test.go:90 +0xdf
  github.com/jaegertracing/jaeger/plugin/storage/integration.(*StorageIntegration).testGetTrace()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/integration/integration_test.go:188 +0x253
  github.com/jaegertracing/jaeger/plugin/storage/integration.(*StorageIntegration).(github.com/jaegertracing/jaeger/plugin/storage/integration.testGetTrace)-fm()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/integration/integration_test.go:378 +0x4b
  testing.tRunner()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0x16d
Previous read at 0x00c420364f2c by goroutine 43:
  internal/race.Read()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/sync/waitgroup.go:70 +0x16e
  github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).handleErrors()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:126 +0x21a
Goroutine 27 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:824 +0x564
  github.com/jaegertracing/jaeger/plugin/storage/integration.TestKafkaStorage()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/integration/kafka_test.go:126 +0x1e5
  testing.tRunner()
      /home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:777 +0x16d
Goroutine 43 (running) created at:
  github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*Consumer).Start.func1()
      /home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/consumer.go:78 +0x175
```
This happens also with the current master sometimes.

**Comment by pavolloffay** [comment]
I will merge as it's a minor change and the one failing which occurred is different one what we are solving here.

**Pull request merged**
