### PR TITLE
Badger persistence queue for agent resubmit

### PR DESCRIPTION
**Pull request by burmanm**
## Which problem is this PR solving?

This PR continues the work from #1733 and adds a persisted queue backed by badger. Still work in progress.

## Short description of the changes
-

### CODE REVIEW

**Comment by objectiser** [comment]
@burmanm Thoughts on pros/cons of the persistent queue?

Pro: Obvious pro is additional capacity for retaining more spans until able to report them to the collector.

Con?: If pod is lost, then could potentially loose a lot of data - but if not able to report it to collector then it would have been lost anyway. This raises the question - if there is a significant backlog, which spans should take priority, the new spans (so that users would see current complete traces more quickly) or just retry in the order they were originally reported?

cc @yurishkuro

**Comment by burmanm** [comment]
Well, I did have (there might be some traces left) a plan to add a "quick-path" for new items, thus they would try to race the open submitter workers and push newest data directly there instead of queue and dequeue. Although this was mostly a performance optimization at first.

But in the end, I feel like it is more consistent to keep the ordering - so that some traces are not just randomly sent (missing spans every now and then). I hope those Jaeger metrics are monitored so that users can see when their agents start to get behind and do something about it. Also, strict ordering makes it easier to guarantee at-least-once delivery.

To combat the "long queue", this does support TTL to the queue so that older spans are simply deleted if they weren't submitted in certain time period.

And as for pods missing, I thought these agents could be run as one per node in Kubernetes? Using persistent disks backing them if necessary (they would return on restart and start submitting traces). At least there's nothing preventing from using them that way.

**Comment by objectiser** [comment]
@burmanm Thanks - do you see any downsides to using the persistent queue over just an in-memory queue? Performance impact?

**Comment by burmanm** [comment]
There's not necessarily any real performance impact (the queue/dequeue doesn't necessarily hit the disk at all) as it's only deserialization / serialization added. Might require some more advanced performance testing to see if in certain situations there could be higher impact (like LSM tree compactions being an issue to someone).

Other than this doesn't support limited count of items in the queue.

**Comment by jpkrohling** [comment]
@burmanm is this something you'd still like to work on ?

**Comment by burmanm** [comment]
I thought this feature was not going to be used in Jaeger? See the "top-PR" comment and closing: https://github.com/jaegertracing/jaeger/issues/1430#issuecomment-631496478

**Comment by jpkrohling** [comment]
True :-) I'm closing this one then.

**Pull request closed without merging**
