### PR TITLE
Fix future release date

### PR DESCRIPTION
**Pull request by Axkea**
## Description of the changes
Change the Tentative release date for version 1.57.0 to 1 May 2024

## How was this change tested?
- 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
please make sure commit is signed

**Comment by albertteoh** [comment]
Oops, thanks @Axkea !

**Review by albertteoh — APPROVED** [review]

**Comment by Axkea** [comment]
@yurishkuro How do I fix this ci problem

**Review by yurishkuro — APPROVED** [review]

**Comment by Axkea** [comment]
Thanks for the merger request, and I will continue to solve some good first issues to help me be selected for GSOC2024

**Pull request merged**
