### PR TITLE
Fix zipkin/jsonv2 that missing parse with traceid.high

### PR DESCRIPTION
**Pull request by moolex**
Signed-off-by: moyo <git@moyo.im>

### CODE REVIEW

**Comment by yurishkuro** [comment]
Is there a test for this code path?

**Comment by yurishkuro** [comment]
LGTM otherwise, thanks for the fix.

**Comment by pavolloffay** [comment]
close-reopen to trigger travis. It seems that travis don't want to test this.

**Comment by yurishkuro** [comment]
done in #596

**Pull request closed without merging**
