### PR TITLE
tmp for share

### PR DESCRIPTION
**Pull request by metapox**
## Which problem is this PR solving?
- 

## Short description of the changes
- 
https://github.com/jaegertracing/jaeger/issues/3949

### CODE REVIEW

**Comment by yurishkuro** [comment]
There is already similar PR #4049, this one does not add anything new, and still has the same issue of not being able to handle batches spans that can be produced by OTEL Collector.

**Comment by yurishkuro** [comment]
Thanks for making OTEL PR, if that one is resolved it would make the Jaeger PR easy.

**Comment by yurishkuro** [comment]
I added more comments to the original PR. I suggest closing this one - if you manage to land the OTEL change, you can take over #4049 to finish it off.

**Comment by metapox** [comment]
Thank you for comment

I had already read [this comment](https://github.com/jaegertracing/jaeger/pull/4049#discussion_r1055437763).

**Pull request closed without merging**
