### PR TITLE
Add OTLP JSON support for Kafka e2e Integration tests

### PR DESCRIPTION
**Pull request by joeyyy09**
## Which problem is this PR solving?
-  This PR addresses the issue of verifying Kafka e2e integration tests for otlp_json formats. 

## Description of the changes
- Verified if the Kafka e2e integration tests run for otlp_json formats.
- Used a fork of mine (github.com/joeyyy09/opentelemetry-collector-contrib) to incorporate necessary changes and verify the process.

## How was this change tested?
- Ran the Kafka e2e integration tests locally using the modified configuration.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
please link to OTEL PR

**Comment by joeyyy09** [comment]
will be good to go after the next release of otel-collector-contrib

**Comment by yurishkuro** [comment]
otel-collector-contrib was upgraded, trying this fix again

**Review by yurishkuro — APPROVED** [review]

**Comment by joeyyy09** [comment]
> otel-collector-contrib was upgraded, trying this fix again

That's great! I think now this is ready to go!

**Comment by yurishkuro** [comment]
🎉

**Pull request merged**
