### PR TITLE
feat: collector to pulsar mq

### PR DESCRIPTION
**Pull request by rfyiamcool**
## Which problem is this PR solving?

Currently, jaeger-collector only supports kafka, but some companies have begun to use pulsar to replace kafka.

I will not discuss the difference between the two in detail here, but what is certain is that pulsar is an excellent mq, as excellent as kafka. 😁

In addition, the company I work for only has pulsar mq, and the kafka cluster has been replaced by pulsar.

😁 Unfortunately, jaeger does not support pulsar, so I submitted this PR.

I first implement the logic about pulsar in the collector. After the PR is merged, I will develop and submit the relevant code about ingester pulsar.

thank you all. 🤝

image

## local test

1. start pulsar (all-in-one) contrainer

```
docker run -d --name pulsar -p 80:80 -p 7654:8080 -p 6650:6650 apachepulsar/pulsar-standalone
```

2. start jaeger collector with pulsar config.

```
SPAN_STORAGE_TYPE=pulsar go run cmd/collector/main.go --pulsar.producer.topic=haha  --pulsar.producer.encoding=json --pulsar.producer.url=pulsar://127.0.0.1:6650
```

3. start pulsar consumer to consume haha topic.

5.  send data to jaeger collector by otel client.

6. pulsar-conumser has consumed trace data that jaeger-collector sent to pulsar.

```
 ./bin/pulsar-client consume haha -s c
...
...
...
...
----- got message -----
key:[f4e3c79b39d1c2ba0c2756e50b127d8a], properties:[], content:{"traceId":"9OPHmznRwroMJ1blCxJ9ig==","spanId":"Y8iHJudNCLQ=","operationName":"Multiplication","startTime":"2023-10-30T03:15:45.544742Z","duration":"0.000003388s","tags":[{"key":"otel.library.name","vStr":"github.com/instrumentron"},{"key":"otel.library.version","vStr":"0.1.0"},{"key":"span.kind","vStr":"internal"},{"key":"internal.span.format","vStr":"otlp"}],"process":{"serviceName":"otlptrace-example","tags":[{"key":"service.version","vStr":"0.0.1"}]}}
11:15:49.582 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://localhost:6650/
11:15:49.586 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [haha] [c] Closed consumer
11:15:49.589 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x8f3dae6b, L:/127.0.0.1:65327 ! R:localhost/127.0.0.1:6650] Disconnected

11:15:51.682 [main] INFO  org.apache.pulsar.client.cli.PulsarClientTool - 1 messages successfully consumed
```

### CODE REVIEW

**Comment by yurishkuro** [comment]
Sorry, but we do not plan supporting pulsar. You may consider converting your code into OpenTelemetry Collector's exporter/receiver and use it there. Once jaeger-v2 is ready you will be able to use those plugins with Jaeger too.

**Comment by yurishkuro** [comment]
In the future you may want to open a ticket first and discuss with maintainers if they are willing to accept such a major feature (applies to any open source project).

**Comment by rfyiamcool** [comment]
😅 That's a shame, I feel like there's still a lot of demand for pulsar.

**Comment by rfyiamcool** [comment]
when is jaeger-v2 ready ?  😁

**Comment by rfyiamcool** [comment]
Your suggestion is that I can develop receiver pulsar and exporter pulsar in otel-collector-contrib ？ 
I found  the kafka receiver and exporter was already in otel-collector-contrib.

**Comment by yurishkuro** [comment]
you don't need to be in otel contrib, can also be in your own repo. Collector allows you to build a version with any modules you like to add.

**Comment by rfyiamcool** [comment]
> you don't need to be in otel contrib, can also be in your own repo. Collector allows you to build a version with any modules you like to add.

Thank you,  I really appreciate your answer.

**Pull request closed without merging**
