### PR TITLE
Reduce CI duration by modifying e2e test execution strategy

### LINKED ISSUE #3068: Document and update integration test with the versions of Kafka Jaeger supports
## Requirement - what kind of business use case are you trying to solve?

Update [jaeger-v2 kafka integration tests][1]  to test with the two most recent versions of Kafka

## Problem - what in Jaeger blocks you from solving the requirement?

Right now we don't mention anywhere in the doc the version of kafka we support. This has lead to multiple open issues: https://github.com/jaegertracing/jaeger/issues/3059 https://github.com/jaegertracing/jaeger/issues/2950  https://github.com/jaegertracing/jaeger/issues/2068

Although [Sarama](https://github.com/Shopify/sarama/) says "Sarama is a Go library for Apache Kafka 0.8, and up." but their [functional tests](https://github.com/Shopify/sarama/blob/master/.github/workflows/ci.yml#L13) only test for kafka v2.7.1 and v2.8.0.

The dependabot or other PR bump up the version of Sarama which may break integration with older version of kafka.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Update kafka integration test for each kafka versions we support just like how we do for ES

## Any open questions to address

This will increase the integration test time but I think we should  do it to prevent unknown breaking changes.

[1]: https://github.com/jaegertracing/jaeger/blob/main/cmd/jaeger/internal/integration/kafka_test.go

### PR DESCRIPTION
**Pull request by zzzk1**
## Which problem is this PR solving?
- Resolves #3068 

## Description of the changes
- old version of the backend storage integration tests runs once daily.
## How was this change tested?
- integration tests

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
I don't understand this PR.

**Comment by zzzk1** [comment]
> I don't understand this PR.

I wish the other version tests would run on the nightly build, but I don't know how to conduct the tests.

**Comment by zzzk1** [comment]
@yurishkuro I apologize for the confusion. I am new to writing pipeline scripts, so could you please provide me with more context? thanks 😊

**Comment by yurishkuro** [comment]
This is not solving any useful problem. We do want all e2e tests to run on PRs. But we don't want to run tests against Kafka v2 because it's EOL.

**Comment by yurishkuro** [comment]
If you don't understand the problem described in the ticket, the best course is to ask clarifying questions, not trying to implement random changes and asking "is this it?"

**Pull request closed without merging**
