### PR TITLE
Fixes #6429 : Reorganize scripts/build folder 

### LINKED ISSUE #6429: Reorganize scripts/ folder
The scripts/ folder accumulated many shell scripts that server different purposes. I propose to categorize them better into subfolders.

 * `adaptive-sampling-integration-test.sh` -> `e2e/adaptive-sampling.sh`
 * `build-all-in-one-image.sh` -> `build/all-in-one-image.sh`
 * `build-crossdock.sh` -> `build/crossdock.sh`
 * `build-hotrod-image.sh` -> `build/hotrod-image.sh`
 * `build-upload-a-docker-image.sh` -> `build/upload-a-docker-image.sh`
 * `build-upload-docker-images.sh` -> `build/upload-docker-images.sh`
 * `cassandra-integration-test.sh` -> `e2e/cassandra.sh`
 * `check-go-version.sh` -> `lint/...`
 * `check-goleak-files.sh` -> `lint/...`
 * `check-semconv-version.sh` -> `lint/...`
 * `check-test-files.sh` -> `lint/...`
 * `clean-binaries.sh` -> `build/...`
 * `compute-tags.sh` -> `util/...`
 * `compute-tags.test.sh` -> `util/...`
 * `dco_check.py` -> `lint/...`
 * `docker-login.sh` -> `util/...`
 * `es-integration-test.sh` -> `e2e/elasticsearch.sh`
 * `import-order-cleanup.py` -> `lint/...`
 * `kafka-integration-test.sh` -> `e2e/kafka.sh`
 * `package-deploy.sh` -> `build/...`
 * `rebuild-ui.sh` -> `build/...`
 * `replace_license_headers.py` -> `lint/...`
 * `spm-integration-test.sh` -> `e2e/spm.sh`
 * `update-semconv-version.sh` -> `lint/...`
 * `updateLicense.py` -> `lint/...`

 * `compute-version.sh --> utils/`
 * `generate-help-output.sh --> utils/`
 * `platforms-to-gh-matrix.sh --> utils/`
 * `upload-docker-readme.sh --> build/`

(`...` means keep the original file name)

Approach:
  * Pick a single category, such as lint or e2e
  * Search the code base for where the file name is used. The most common locations are the makefiles, .github/workflows/, and other scripts
  * Move/rename scripts **for a single category** and update places where they are called

Categories:
  * [x] `e2e/*`
  * [x] `lint/*`
  * [x] `build/*`
  * [ ] `utils/*`

### PR DESCRIPTION
**Pull request by Ashu463**
## Which problem is this PR solving?
- Fix #6429 

## Description of the changes
- In this PR all scripts of build category moved to `build/` folder. 

## How was this change tested?
- Attaching screenshot : 
image

## Checklist
- [X] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [X] I have signed all commits
- [ ] I have added unit tests for the new functionality ~ not needed 
- [ ] I have run lint and test steps successfully ~ not needed 
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

**Comment by lekaf974** [comment]
@Ashu463 you need to amend your PR and signoff to fix DCO error

**Comment by Ashu463** [comment]
> @Ashu463 you need to amend your PR and signoff to fix DCO error
> 
> Also did you update the files that were calling those scripts ?

Hey @lekaf974 how would I do the same, could you help me ?

**Comment by yurishkuro** [comment]
See CONTRIBUTING_GUIDELINES.md for DCO check

**Comment by lekaf974** [comment]
you could try `git commit --amend --signoff`

**Comment by lekaf974** [comment]
@Ashu463 you also need to update files referring to those scripts

**Comment by Ashu463** [comment]
@lekaf974 what files am I supposed to update ? as per the description I just have to manage folder structure of `scripts/`

**Comment by yurishkuro** [comment]
> as per the description I just have to manage folder structure of scripts/

This is not what the description says. If this was just a matter of moving the files I would not have opened the issue. Moving the scripts breaks the other scripts than depend on them, so the references to the moved files need to be updated. I closed all other PRs until at least one is actually done right, to remove noise and distraction.

**Comment by Ashu463** [comment]
Ah you were asking in that way, will fix this soon. It all seems fine while running `tests`, but if there any other way to test out repository then please let me know.  
Thanks !

**Comment by yurishkuro** [comment]
> if there any other way to test out repository then please let me know.

all integration tests are invoked from .github/workflows, you can see how it's done (there isn't a single command for that).

**Comment by yurishkuro** [comment]
@Ashu463 you don't need to run all CI tests locally to solve this issue - you can simply grep the repository for the file names of the scripts, and replace all occurrences. Then once you submit a PR we will run full CI to validate that nothing was misssed.

**Comment by lekaf974** [comment]
@Ashu463 I can raise a PR for this build folder then you could take it as example for the other one ?

**Comment by yurishkuro** [comment]
solved in #6446

**Comment by Ashu463** [comment]
@yurishkuro good to see this. Is he raised for other ones ?

**Pull request closed without merging**
