### PR TITLE
Preparing release 1.7.0

### PR DESCRIPTION
**Pull request by pavolloffay**
Depends on https://github.com/jaegertracing/jaeger/pull/1061, https://github.com/jaegertracing/jaeger/pull/1062

Preparation for 1.7 release. Tag some features as experimental.

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
I will add also the changelog changes and do the release after this is merged.

**Comment by pavolloffay** [comment]
@tiffon could you please check UI changes?

**Comment by objectiser** [comment]
@pavolloffay The [standalone-linux](https://github.com/jaegertracing/jaeger/blob/master/cmd/all-in-one/standalone-linux) has been committed as part of #1062.

**Comment by pavolloffay** [comment]
@objectiser thanks for the notification.

**Pull request merged**
