### PR TITLE
Update Jaeger community support URL

### PR DESCRIPTION
**Pull request by albertteoh**
Signed-off-by: albertteoh <albert.teoh@logz.io>

## Which problem is this PR solving?
From Gitter -> Slack.

URL obtained by right-clicking #jaeger channel -> "Copy link".

### CODE REVIEW

**Comment by yurishkuro** [comment]
There's more than one reference:
```
./README.md:4:[![Gitter chat][gitter-img]][gitter]
./README.md:166: * [Gitter chat room](https://gitter.im/jaegertracing/Lobby)
./README.md:197:[gitter]: https://gitter.im/jaegertracing/Lobby
./README.md:198:[gitter-img]: https://img.shields.io/badge/gitter-join%20chat%20%E2%86%92-brightgreen.svg
./RELEASE.md:25:6. Announce the release on the [mailing list](https://groups.google.com/g/jaeger-tracing), [gitter](https://gitter.im/jaegertracing/Lobby), and [twitter](https://twitter.com/JaegerTracing?lang=en).
./.github/ISSUE_TEMPLATE/feature_request.md:17:    - our chat room https://gitter.im/jaegertracing/Lobby, or
./.github/ISSUE_TEMPLATE/config.yml:4:    url: https://gitter.im/jaegertracing/Lobby
./SECURITY.md:18:* Contact us on our open chat room on [Gitter][gitter-room]
./SECURITY.md:19:* If you can't use Gitter, send a message to [jaeger-tracing@googlegroups.com][mailing-list]
./SECURITY.md:20:* If you can't use Gitter nor send an email, open a merge request on GitHub: fork the affected repository and send us a pull request. We really prefer if you'd talk to us before, though, as our repositories are public and we would like to give a heads up to our users before disclosing it publicly
./SECURITY.md:94:[gitter-room]: https://gitter.im/jaegertracing/Lobby
```

See also https://github.com/jaegertracing/documentation/issues/478

**Comment by albertteoh** [comment]
Thanks for pointing that out @yurishkuro, I'll update those other refs too.

**Comment by jpkrohling** [comment]
Related to this: https://github.com/jaegertracing/documentation/issues/478

**Comment by jpkrohling** [comment]
Apparently, there's still one:

```
./idl/.github/ISSUE_TEMPLATE.md:    - our chat room https://gitter.im/jaegertracing/Lobby, or
```

**Comment by albertteoh** [comment]
> Apparently, there's still one reference left:
> 
> ```
> ./idl/.github/ISSUE_TEMPLATE.md:    - our chat room https://gitter.im/jaegertracing/Lobby, or
> ```

@jpkrohling I think `idl` is a submodule pointing to another repo: https://github.com/jaegertracing/jaeger-idl and so I'll need to create a separate PR there, along with jaeger-ui. I'll create an issue ticket to track what needs to change.

**Comment by jpkrohling** [comment]
Yes, sorry, not enough coffee today. LGTM

**Pull request merged**
