### PR TITLE
Remove deprecated --jaeger.tags CLI flag

### PR DESCRIPTION
**Pull request by yurishkuro**
Resolves part of #2738

### CODE REVIEW

**Comment by yurishkuro** [comment]
@jpkrohling any concerns with the changes to OTEL part?

**Review by jpkrohling — APPROVED** [review]
LGTM

**Comment by jpkrohling** [comment]
`codecov/patch` is still running (!!). Will merge on green.

**Comment by yurishkuro** [comment]
codecov has been glitchy the past few days, the logs already show the report, but status not updated.

**Pull request merged**
