### PR TITLE
Limit URL size in Elasticsearch index delete request

### LINKED ISSUE #3374: es index deletion failed with too_long_frame_exception
**Describe the bug**
Index deletion process failed when the delete request contains more than 4096 chars

#### Config:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: es-rollover
spec:
  ingress:
    security: none
  strategy: production
  storage:
    esIndexCleaner:
      enabled: true
      schedule: "* */12 * * *"
      numberOfDays: 1
    esRollover:
      schedule: "*/1 * * * *"
      conditions: '{"max_age":"1m"}'
      readTTL: 1m
    type: elasticsearch
    options:
      es.use-aliases: true
    elasticsearch:
      nodeCount: 1
      storage:
        storageClassName: "standard"
        size: "5G"
      resources:
        requests:
          memory: "1Gi"
          cpu: "510m"
        limits:
          memory: "1Gi"
```

**Expected behavior**
should be deleted the requested indices

**Screenshots**

**Version (please complete the following information):**
 - OS: Linux
 - Jaeger version: 1.26.0
 - Deployment: OCP 4.9

#### Error:
```
Error: failed to delete indices: jaeger-service-000132,jaeger-service-000143,jaeger-span-000158,jaeger-span-000176,jaeger-span-000351,jaeger-service-000216,jaeger-span-000031,jaeger-span-000267,jaeger-service-000158,jaeger-span-000071,jaeger-service-000439,jaeger-span-000074,jaeger-service-000190,jaeger-service-000406,jaeger-service-000161,jaeger-service-000244,jaeger-service-000379,jaeger-span-000121,jaeger-service-000411,jaeger-span-000280,jaeger-service-000187,jaeger-service-000343,jaeger-span-000424,jaeger-service-000498,jaeger-span-000321,jaeger-service-000241,jaeger-span-000379,jaeger-service-000316,jaeger-span-000288,jaeger-span-000052,jaeger-span-000206,jaeger-service-000112,jaeger-service-000236,jaeger-span-000106,jaeger-service-000141,jaeger-service-000146,jaeger-span-000201,jaeger-span-000281,jaeger-service-000288,jaeger-span-000162,jaeger-span-000120,jaeger-service-000166,jaeger-service-000452,jaeger-span-000114,jaeger-span-000387,jaeger-service-000425,jaeger-span-000078,jaeger-span-000405,jaeger-service-000387,jaeger-service-000448,jaeger-span-000241,jaeger-service-000120,jaeger-span-000039,jaeger-service-000267,jaeger-service-000279,jaeger-span-000190,jaeger-span-000268,jaeger-service-000335,jaeger-service-000500,jaeger-span-000119,jaeger-span-000128,jaeger-service-000262,jaeger-span-000059,jaeger-service-000470,jaeger-span-000011,jaeger-span-000112,jaeger-span-000196,jaeger-service-000245,jaeger-service-000359,jaeger-service-000426,jaeger-span-000440,jaeger-service-000179,jaeger-service-000200,jaeger-span-000322,jaeger-span-000374,jaeger-service-000203,jaeger-span-000209,jaeger-span-000215,jaeger-service-000295,jaeger-span-000266,jaeger-span-000420,jaeger-service-000383,jaeger-span-000186,jaeger-service-000298,jaeger-service-000303,jaeger-span-000414,jaeger-service-000266,jaeger-span-000020,jaeger-span-000269,jaeger-service-000131,jaeger-service-000284,jaeger-span-000324,jaeger-span-000174,jaeger-span-000314,jaeger-span-000134,jaeger-span-000425,jaeger-service-000253,jaeger-service-000395,jaeger-span-000402,jaeger-service-000069,jaeger-service-000317,jaeger-service-000092,jaeger-service-000204,jaeger-span-000224,jaeger-span-000352,jaeger-service-000356,jaeger-service-000471,jaeger-span-000057,jaeger-span-000347,jaeger-span-000355,jaeger-service-000449,jaeger-span-000029,jaeger-span-000326,jaeger-span-000336,jaeger-service-000496,jaeger-span-000214,jaeger-span-000408,jaeger-span-000145,jaeger-span-000217,jaeger-span-000231,jaeger-span-000304,jaeger-span-000415,jaeger-service-000104,jaeger-service-000475,jaeger-span-000102,jaeger-span-000303,jaeger-span-000332,jaeger-service-000110,jaeger-service-000199,jaeger-span-000006,jaeger-span-000065,jaeger-span-000164,jaeger-service-000087,jaeger-service-000454,jaeger-service-000109,jaeger-service-000389,jaeger-span-000027,jaeger-service-000084,jaeger-service-000269,jaeger-span-000086,jaeger-span-000007,jaeger-span-000037,jaeger-span-000004,jaeger-span-000173,jaeger-span-000433,jaeger-service-000171,jaeger-service-000202,jaeger-span-000192,jaeger-span-000308,jaeger-span-000397,jaeger-service-000418,jaeger-span-000155,jaeger-service-000330,jaeger-service-000074,jaeger-service-000142,jaeger-span-000441,jaeger-service-000095,jaeger-service-000167,jaeger-service-000130,jaeger-service-000372,jaeger-service-000423,jaeger-service-000507,jaeger-span-000073,jaeger-span-000144,jaeger-span-000183,jaeger-service-000329,jaeger-service-000331,jaeger-span-000002,jaeger-span-000262,jaeger-service-000505,jaeger-span-000026,jaeger-span-000088,jaeger-span-000216,jaeger-service-000442,jaeger-service-000462,jaeger-span-000289,jaeger-service-000287,jaeger-service-000311,jaeger-service-000370,jaeger-service-000376,jaeger-span-000235,jaeger-service-000137,jaeger-service-000285,jaeger-service-000124,jaeger-span-000091,jaeger-service-000223,jaeger-service-000433,jaeger-span-000409,jaeger-service-000121,jaeger-service-000264,jaeger-span-000276,jaeger-service-000231,jaeger-service-000380,jaeger-service-000224,jaeger-service-000467,jaeger-service-000494,jaeger-span-000275,jaeger-span-000392,jaeger-service-000067,jaeger-service-000071,jaeger-span-000111,jaeger-span-000367,jaeger-service-000177,jaeger-span-000181,jaeger-span-000315,jaeger-span-000427,jaeger-service-000075,jaeger-service-000226,jaeger-service-000276,jaeger-service-000306,jaeger-span-000378,jaeger-service-000491,jaeger-span-000063,jaeger-span-000069,jaeger-span-000239,jaeger-span-000254,jaeger-service-000080,jaeger-service-000274,jaeger-service-000232,jaeger-service-000321,jaeger-service-000358,jaeger-service-000364,jaeger-span-000246,jaeger-service-000150,jaeger-service-000155,jaeger-span-000003,jaeger-span-000137,jaeger-service-000417,jaeger-service-000441,jaeger-service-000381,jaeger-span-000116,jaeger-service-000327,jaeger-service-000354,jaeger-span-000252,jaeger-service-000147,jaeger-service-000318,jaeger-span-000195,jaeger-service-000219,jaeger-span-000005,jaeger-span-000035,jaeger-span-000092,jaeger-span-000338,jaeger-span-000413,jaeger-service-000218,jaeger-service-000280,jaeger-span-000157,jaeger-span-000182,jaeger-service-000315,jaeger-span-000077,jaeger-span-000272,jaeger-service-000326,jaeger-span-000189,jaeger-span-000167,jaeger-span-000282,jaeger-service-000079,jaeger-service-000172,jaeger-span-000283,jaeger-span-000386,jaeger-service-000457,jaeger-span-000170,jaeger-span-000109,jaeger-span-000148,jaeger-service-000098,jaeger-service-000286,jaeger-span-000274,jaeger-service-000175,jaeger-service-000352,jaeger-span-000146,jaeger-service-000404,jaeger-span-000139,jaeger-service-000357,jaeger-span-000095,jaeger-span-000218,jaeger-span-000293,jaeger-span-000349,jaeger-service-000113,jaeger-service-000157,jaeger-span-000340,jaeger-service-000127,jaeger-service-000407,jaeger-service-000399,jaeger-span-000342,jaeger-span-000296,jaeger-service-000466,jaeger-service-000469,jaeger-service-000453,jaeger-service-000135,jaeger-service-000396,jaeger-span-000151,jaeger-service-000126,jaeger-service-000145,jaeger-service-000419,jaeger-service-000192,jaeger-service-000198,jaeger-span-000302,jaeger-span-000404,jaeger-service-000271,jaeger-service-000504,jaeger-span-000038,jaeger-span-000165,jaeger-service-000506,jaeger-span-000066,jaeger-service-000234,jaeger-service-000432,jaeger-service-000332,jaeger-span-000375,jaeger-span-000021,jaeger-span-000399,jaeger-service-000351,jaeger-span-000024,jaeger-span-000115,jaeger-span-000169,jaeger-service-000128,jaeger-service-000186,jaeger-span-000103,jaeger-service-000301,jaeger-service-000458,jaeger-service-000324,jaeger-span-000030,jaeger-span-000429,jaeger-service-000196,jaeger-service-000213,jaeger-span-000295,jaeger-service-000508,jaeger-span-000270,jaeger-service-000483,jaeger-span-000442,jaeger-service-000348,jaeger-span-000335,jaeger-span-000371,jaeger-service-000073,jaeger-service-000090,jaeger-span-000238,jaeger-service-000424,jaeger-service-000497,jaeger-span-000294,jaeger-span-000334,jaeger-span-000080,jaeger-service-000235,jaeger-service-000275,jaeger-span-000076,jaeger-service-000341,jaeger-service-000353,jaeger-span-000008,jaeger-span-000257,jaeger-span-000221,jaeger-span-000443,jaeger-service-000486,jaeger-span-000198,jaeger-service-000325,jaeger-span-000100,jaeger-span-000310,jaeger-service-000170,jaeger-service-000201,jaeger-span-000398,jaeger-service-000180,jaeger-service-000479,jaeger-service-000413,jaeger-service-000421,jaeger-span-000188,jaeger-span-000193,jaeger-span-000259,jaeger-span-000435,jaeger-service-000139,jaeger-span-000104,jaeger-span-000372,jaeger-service-000252,jaeger-service-000367,jaeger-service-000443,jaeger-service-000485,jaeger-span-000084,jaeger-span-000316,jaeger-span-000388,jaeger-service-000116,jaeger-service-000283,jaeger-span-000410,jaeger-span-000079,jaeger-span-000161,jaeger-span-000227,jaeger-span-000237,jaeger-service-000114,jaeger-service-000304,jaeger-service-000375,jaeger-span-000382,jaeger-span-000016,jaeger-span-000154,jaeger-service-000230,jaeger-service-000398,jaeger-service-000472,jaeger-span-000187,jaeger-service-000178,jaeger-service-000342,jaeger-service-000108,jaeger-span-000412,jaeger-service-000229,jaeger-span-000323,jaeger-span-000423,jaeger-service-000270,jaeger-span-000395,jaeger-service-000440,jaeger-span-000439,jaeger-span-000263,jaeger-service-000369,jaeger-span-000156,jaeger-span-000107,jaeger-span-000138,jaeger-service-000420,jaeger-service-000431,jaeger-service-000428,jaeger-span-000258,jaeger-span-000319,jaeger-service-000123,jaeger-span-000083,jaeger-span-000260,jaeger-span-000364,jaeger-span-000126,jaeger-span-000010,jaeger-span-000108,jaeger-span-000150,jaeger-span-000177,jaeger-service-000138,jaeger-service-000477,jaeger-span-000251,jaeger-service-000371,jaeger-span-000015,jaeger-span-000394,jaeger-span-000248,jaeger-span-000422,jaeger-service-000081,jaeger-span-000147,jaeger-service-000107,jaeger-service-000363,jaeger-service-000385,jaeger-service-000427,jaeger-service-000438,jaeger-service-000001,jaeger-service-000106,jaeger-span-000087,jaeger-service-000169,jaeger-service-000251,jaeger-service-000239,jaeger-span-000273,jaeger-span-000264,jaeger-service-000501,jaeger-span-000168,jaeger-service-000412,jaeger-service-000333,jaeger-service-000365,jaeger-span-000389,jaeger-service-000503,jaeger-span-000233,jaeger-service-000323,jaeger-span-000061,jaeger-service-000362,jaeger-span-000110,jaeger-span-000055,jaeger-span-000117,jaeger-span-000122,jaeger-span-000416,jaeger-service-000307,jaeger-span-000025,jaeger-span-000418,jaeger-service-000256,jaeger-service-000290,jaeger-service-000463,jaeger-service-000099,jaeger-service-000345,jaeger-service-000482,jaeger-span-000096,jaeger-service-000133,jaeger-service-000302,jaeger-span-000070,jaeger-span-000333,jaeger-service-000340,jaeger-service-000414,jaeger-service-000299,jaeger-service-000490,jaeger-span-000428,jaeger-service-000207,jaeger-service-000268,jaeger-span-000067,jaeger-span-000132,jaeger-service-000368,jaeger-service-000450,jaeger-service-000197,jaeger-span-000381,jaeger-span-000082,jaeger-span-000362,jaeger-service-000242,jaeger-span-000101,jaeger-span-000277,jaeger-span-000411,jaeger-service-000160,jaeger-service-000384,jaeger-span-000344,jaeger-service-000320,jaeger-service-000447,jaeger-service-000502,jaeger-span-000391,jaeger-service-000115,jaeger-service-000499,jaeger-span-000056,jaeger-span-000060,jaeger-span-000255,jaeger-span-000286,jaeger-span-000350,jaeger-span-000356,jaeger-service-000102,jaeger-service-000165,jaeger-span-000359,jaeger-span-000384,jaeger-service-000493,jaeger-span-000219,jaeger-span-000365,jaeger-service-000182,jaeger-service-000319,jaeger-service-000159,jaeger-service-000294,jaeger-service-000151,jaeger-service-000254,jaeger-service-000481,jaeger-span-000299,jaeger-service-000209,jaeger-service-000339,jaeger-span-000197,jaeger-span-000298,jaeger-span-000380,jaeger-service-000129,jaeger-service-000480,jaeger-span-000023,jaeger-span-000271,jaeger-service-000085,jaeger-service-000250,jaeger-span-000013,jaeger-span-000036,jaeger-span-000301,jaeger-span-000377,jaeger-service-000162,jaeger-span-000204,jaeger-span-000292,jaeger-service-000152,jaeger-service-000278,jaeger-service-000263,jaeger-span-000018,jaeger-span-000053,jaeger-service-000176,jaeger-service-000416,jaeger-span-000194,jaeger-service-000168,jaeger-span-000040,jaeger-service-000181,jaeger-service-000258,jaeger-span-000184,jaeger-service-000094,jaeger-service-000097,jaeger-span-000253,jaeger-service-000435,jaeger-span-000142,jaeger-span-000075,jaeger-span-000354,jaeger-service-000308,jaeger-service-000437,jaeger-span-000149,jaeger-span-000223,jaeger-span-000361,jaeger-service-000217,jaeger-span-000054,jaeger-span-000211,jaeger-span-000343,jaeger-service-000105,jaeger-service-000156,jaeger-service-000360,jaeger-span-000247,jaeger-span-000406,jaeger-service-000122,jaeger-service-000144,jaeger-span-000437,jaeger-service-000265,jaeger-span-000135,jaeger-span-000152,jaeger-span-000240,jaeger-service-000401,jaeger-span-000044,jaeger-span-000200,jaeger-span-000213,jaeger-span-000357,jaeger-service-000100,jaeger-span-000058,jaeger-service-000473,jaeger-span-000046,jaeger-span-000368,jaeger-service-000070,jaeger-service-000293,jaeger-span-000019,jaeger-span-000048,jaeger-service-000456,jaeger-span-000290,jaeger-span-000129,jaeger-span-000143,jaeger-span-000203,jaeger-span-000212,jaeger-span-000226,jaeger-span-000043,jaeger-span-000099,jaeger-span-000050,jaeger-span-000331,jaeger-service-000193,jaeger-service-000297,jaeger-service-000488,jaeger-span-000047,jaeger-span-000085,jaeger-span-000430,jaeger-service-000247,jaeger-service-000461,jaeger-span-000199,jaeger-span-000417,jaeger-span-000390,jaeger-span-000287,jaeger-span-000348,jaeger-service-000243,jaeger-span-000045,jaeger-span-000385,jaeger-service-000459,jaeger-span-000307,jaeger-span-000393,jaeger-span-000407,jaeger-span-000421,jaeger-span-000125,jaeger-span-000225,jaeger-service-000388,jaeger-span-000426,jaeger-service-000072,jaeger-service-000117,jaeger-service-000444,jaeger-service-000510,jaeger-span-000089,jaeger-span-000191,jaeger-span-000208,jaeger-span-000265,jaeger-service-000334,jaeger-service-000349,jaeger-span-000049,jaeger-span-000097,jaeger-span-000317,jaeger-service-000210,jaeger-service-000484,jaeger-span-000325,jaeger-service-000257,jaeger-service-000314,jaeger-service-000446,jaeger-service-000455,jaeger-span-000234,jaeger-service-000089,jaeger-span-000140,jaeger-service-000430,jaeger-span-000041,jaeger-span-000178,jaeger-span-000309,jaeger-service-000214,jaeger-service-000228,jaeger-service-000212,jaeger-service-000238,jaeger-service-000309,jaeger-service-000408,jaeger-span-000017,jaeger-span-000228,jaeger-service-000082,jaeger-service-000205,jaeger-span-000256,jaeger-span-000318,jaeger-service-000393,jaeger-span-000068,jaeger-service-000240,jaeger-span-000345,jaeger-service-000164,jaeger-service-000233,jaeger-span-000133,jaeger-span-000436,jaeger-service-000445,jaeger-span-000072,jaeger-span-000131,jaeger-service-000355,jaeger-span-000012,jaeger-span-000312,jaeger-service-000191,jaeger-service-000386,jaeger-span-000113,jaeger-service-000312,jaeger-service-000468,jaeger-span-000320,jaeger-span-000438,jaeger-service-000189,jaeger-service-000292,jaeger-service-000451,jaeger-span-000306,jaeger-span-000329,jaeger-service-000282,jaeger-span-000130,jaeger-span-000062,jaeger-span-000220,jaeger-span-000300,jaeger-service-000134,jaeger-service-000248,jaeger-span-000123,jaeger-service-000291,jaeger-span-000028,jaeger-service-000237,jaeger-service-000259,jaeger-service-000465,jaeger-span-000261,jaeger-service-000076,jaeger-service-000101,jaeger-service-000373,jaeger-service-000403,jaeger-span-000160,jaeger-service-000078,jaeger-service-000154,jaeger-span-000373,jaeger-service-000347,jaeger-span-000360,jaeger-span-000093,jaeger-span-000171,jaeger-service-000378,jaeger-service-000474,jaeger-service-000377,jaeger-service-000392,jaeger-span-000353,jaeger-service-000272,jaeger-service-000344,jaeger-span-000179,jaeger-span-000339,jaeger-service-000173,jaeger-service-000382,jaeger-service-000260,jaeger-service-000289,jaeger-service-000410,jaeger-span-000245,jaeger-span-000297,jaeger-service-000328,jaeger-service-000350,jaeger-service-000476,jaeger-span-000285,jaeger-span-000313,jaeger-span-000434,jaeger-service-000366,jaeger-service-000460,jaeger-service-000313,jaeger-service-000300,jaeger-service-000489,jaeger-service-000322,jaeger-service-000337,jaeger-service-000429,jaeger-span-000172,jaeger-span-000202,jaeger-span-000210,jaeger-service-000255,jaeger-service-000261,jaeger-span-000432,jaeger-span-000127,jaeger-service-000249,jaeger-span-000009,jaeger-span-000098,jaeger-span-000105,jaeger-span-000222,jaeger-service-000227,jaeger-service-000281,jaeger-span-000034,jaeger-span-000064,jaeger-span-000311,jaeger-service-000390,jaeger-service-000394,jaeger-span-000291,jaeger-service-000277,jaeger-span-000180,jaeger-service-000125,jaeger-service-000415,jaeger-span-000249,jaeger-service-000405,jaeger-span-000232,jaeger-span-000205,jaeger-span-000229,jaeger-service-000184,jaeger-service-000188,jaeger-span-000279,jaeger-span-000327,jaeger-span-000366,jaeger-service-000305,jaeger-service-000422,jaeger-span-000236,jaeger-span-000346,jaeger-service-000093,jaeger-service-000273,jaeger-span-000185,jaeger-service-000464,jaeger-service-000509,jaeger-span-000341,jaeger-service-000402,jaeger-service-000487,jaeger-service-000163,jaeger-service-000222,jaeger-service-000077,jaeger-service-000136,jaeger-service-000225,jaeger-service-000361,jaeger-service-000478,jaeger-service-000495,jaeger-service-000140,jaeger-service-000195,jaeger-span-000400,jaeger-service-000221,jaeger-span-000175,jaeger-service-000374,jaeger-span-000001,jaeger-span-000014,jaeger-span-000159,jaeger-span-000284,jaeger-span-000370,jaeger-service-000211,jaeger-service-000346,jaeger-service-000338,jaeger-span-000369,jaeger-service-000391,jaeger-service-000434,jaeger-span-000278,jaeger-span-000330,jaeger-span-000383,jaeger-service-000119,jaeger-service-000296,jaeger-span-000022,jaeger-span-000403,jaeger-service-000083,jaeger-service-000220,jaeger-span-000033,jaeger-span-000124,jaeger-span-000136,jaeger-span-000166,jaeger-service-000149,jaeger-service-000436,jaeger-span-000358,jaeger-span-000401,jaeger-span-000244,jaeger-span-000081,jaeger-span-000141,jaeger-span-000153,jaeger-service-000096,jaeger-service-000118,jaeger-span-000032,jaeger-service-000153,jaeger-service-000397,jaeger-service-000103,jaeger-service-000148,jaeger-span-000328,jaeger-service-000336,jaeger-service-000088,jaeger-service-000206,jaeger-span-000242,jaeger-span-000431,jaeger-service-000174,jaeger-service-000409,jaeger-service-000400,jaeger-span-000118,jaeger-service-000068,jaeger-service-000194,jaeger-service-000246,jaeger-span-000051,jaeger-span-000337,jaeger-span-000419,jaeger-service-000185,jaeger-service-000208,jaeger-service-000111,jaeger-service-000183,jaeger-service-000492,jaeger-span-000090,jaeger-span-000163,jaeger-span-000250,jaeger-service-000091,jaeger-service-000215,jaeger-span-000094,jaeger-span-000243,jaeger-span-000376,jaeger-service-000086,jaeger-span-000363,jaeger-span-000230,jaeger-span-000305,jaeger-span-000396,jaeger-service-000310,jaeger-span-000042,jaeger-span-000207,, request failed, status code: 400, body: {"error":{"root_cause":[{"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."}],"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."},"status":400}
Usage:
  jaeger-es-index-cleaner NUM_OF_DAYS http://HOSTNAME:PORT [flags]

Flags:
      --archive                       Whether to remove archive indices. It works only for rollover
      --es.password string            The password required by storage
      --es.tls.ca string              Path to a TLS CA (Certification Authority) file used to verify the remote server(s) (by default will use the system truststore)
      --es.tls.cert string            Path to a TLS Certificate file, used to identify this process to the remote server(s)
      --es.tls.enabled                Enable TLS when talking to the remote server(s)
      --es.tls.key string             Path to a TLS Private Key file, used to identify this process to the remote server(s)
      --es.tls.server-name string     Override the TLS server name we expect in the certificate of the remote server(s)
      --es.tls.skip-host-verify       (insecure) Skip server's certificate chain and host name verification
      --es.username string            The username required by storage
  -h, --help                          help for jaeger-es-index-cleaner
      --index-date-separator string   Index date separator (default "-")
      --index-prefix string           Index prefix
      --rollover                      Whether to remove indices created by rollover
      --timeout int                   Number of seconds to wait for master node response (default 120)
```

pod log: 
[es-rollover-es-index-cleaner-27265019--1-29264-es-rollover-es-index-cleaner.log](https://github.com/jaegertracing/jaeger/files/7466433/es-rollover-es-index-cleaner-27265019--1-29264-es-rollover-es-index-cleaner.log)

### PR DESCRIPTION
**Pull request by jkandasa**
Signed-off-by: Jeeva Kandasamy <jkandasa@gmail.com>

## Which problem is this PR solving?
- Resolves #3374

### CODE REVIEW

**Comment by jkandasa** [comment]
@pavolloffay can you please review this?

**Review by pavolloffay — DISMISSED** [review]
It would be great if you could add as well integration test for this to https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/integration/es_index_cleaner_test.go

**Comment by jkandasa** [comment]
> It would be great if you could add as well integration test for this to https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/integration/es_index_cleaner_test.go

@pavolloffay I do not see an option to create indices with past `creation_time`. 
Can you guide me to get those? Thanks!

**Comment by jkandasa** [comment]
@pavolloffay I have added additional unit tests to cover the es index delete functionality

**Comment by pavolloffay** [comment]
> @pavolloffay I do not see an option to create indices with past creation_time.
Can you guide me to get those? Thanks!

IIRC that is not required to test this feature.

**Review by pavolloffay — APPROVED** [review]

**Comment by pavolloffay** [comment]
thanks @jkandasa for the contribution

**Pull request merged**
