### PR TITLE
Fix gRPC query service cmux

### PR DESCRIPTION
**Pull request by 32leaves**
fixes https://github.com/jaegertracing/jaeger/issues/1754

breaking change: https://github.com/grpc/grpc-go/issues/2406
workaround described in:
- https://github.com/soheilhy/cmux/issues/64
- https://github.com/soheilhy/cmux#limitations

### CODE REVIEW

**Comment by yurishkuro** [comment]
Thanks for the research & the fix, @32leaves .

I would like to have a unit test that uses grpc client to hit grpc endpoint via cmux, so that we don't have regressions like these in the future.

**Comment by yurishkuro** [comment]
I don't think this fix is helping, I added a unit test #1758 for connecting to grpc server via cmux, and it's failing both before and after the change to matchers. Also, the behavioral change in https://github.com/grpc/grpc-go/issues/2406 was only released in grpc-go 1.23, but we're currently pinning grpc to 1.21.1

**Comment by yurishkuro** [comment]
cc @annanay25

**Comment by 32leaves** [comment]
I just pushed the test I used while working on the fix (didn't see you had already added a test as well - I'm happy to remove mine again). With this fix I can successfully call `GetServices` using the gRPC interface.

**Comment by annanay25** [comment]
Thanks for the PR @32leaves. Travis is failing with - 
```
cmd/query/app/server_test.go:69:97: grpc.WithTimeout is deprecated: use DialContext and context.WithTimeout instead.  (SA1019)
```

We should be able to go forward and land once this is fixed :)  
Ref: #1758

**Comment by yurishkuro** [comment]
My mistake, my PR was using the wrong port.

It's fixed now, I prefer to merge my PR because it includes a bunch of other clean-up. I pulled the main commit from here for the actual fix.

**Comment by yurishkuro** [comment]
superseded by #1758

**Pull request closed without merging**
