### PR TITLE
Tracegen supports generating firehose spans

### PR DESCRIPTION
**Pull request by guo0693**
- add 'firehose' flag for tracegen
- upgrade jaeger-client-go version to 2.18.0

Signed-off-by: jung <jung@uber.com>

## Which problem is this PR solving?
- Relates to #1731 

## Short description of the changes
-

### CODE REVIEW

**Comment by guo0693** [comment]
Screen Shot 2019-09-13 at 12 59 48

Tested using all-in-one, the flag is correctly set.

**Comment by guo0693** [comment]
Seems like codecov got stuck

**Comment by yurishkuro** [comment]
I restarted COVER build

**Comment by vprithvi** [comment]
Looks like a ES flaky test similar to #1713 

```
--- FAIL: TestSpanReader_multiRead_followUp_query (0.00s)
panic: 
mock: Unexpected Method Call
-----------------------------
Index(string,string)
		0: "jaeger-span-2019-09-14"
		1: "jaeger-span-2019-09-13"
The closest call I have is: 
Index(mock.AnythingOfTypeArgument)
		0: "string"
Provided 1 arguments, mocked for 2 arguments
Diff: 1: FAIL:  (string=jaeger-span-2019-09-13) != (Missing) [recovered]
	panic: 
mock: Unexpected Method Call
-----------------------------
Index(string,string)
		0: "jaeger-span-2019-09-14"
		1: "jaeger-span-2019-09-13"
The closest call I have is: 
Index(mock.AnythingOfTypeArgument)
		0: "string"
Provided 1 arguments, mocked for 2 arguments
Diff: 1: FAIL:  (string=jaeger-span-2019-09-13) != (Missing)
goroutine 22 [running]:
testing.tRunner.func1(0xc000112700)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:830 +0x69d
panic(0xccac80, 0xc00012bbb0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock.(*Mock).fail(0xc0000d9270, 0xdc5b58, 0x6f, 0xc00013fac0, 0x4, 0x4)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock/mock.go:236 +0x1ad
github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock.(*Mock).MethodCalled(0xc0000d9270, 0x13e789b, 0x5, 0xc0001823a0, 0x2, 0x2, 0xc00013fa80, 0x4, 0x4)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock/mock.go:366 +0x4e3
github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock.(*Mock).Called(0xc0000d9270, 0xc0001823a0, 0x2, 0x2, 0xc000182380, 0x2, 0x2)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/stretchr/testify/mock/mock.go:338 +0x1e7
github.com/jaegertracing/jaeger/pkg/es/mocks.(*MultiSearchService).Index(0xc0000d9270, 0xc000182220, 0x2, 0x2, 0x2b0b4b9ad130, 0xc0000d9270)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/es/mocks/MultiSearchService.go:87 +0x1c6
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanReader).multiRead(0xc00012ec00, 0xe99140, 0xc0000a2010, 0xc0000d5a00, 0x2, 0x2, 0xbf572a6c55fd7043, 0x912e74, 0x145bcc0, 0xbf572a6c55fd7043, ...)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader.go:340 +0xd30
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.TestSpanReader_multiRead_followUp_query.func1(0xc0000b3fe0)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader_test.go:267 +0x23cb
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.withSpanReader(0xc000060f50)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader_test.go:106 +0x382
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.TestSpanReader_multiRead_followUp_query(0xc000112700)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/reader_test.go:210 +0x57
testing.tRunner(0xc000112700, 0xdca1c0)
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/testing/testing.go:916 +0x65b
FAIL	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore	0.022s
make: *** [cover] Error 1
The command "if [ "$TESTS" == true ]; then make test-ci ; else echo 'skipping tests'; fi" exited with 2.
```

**Pull request merged**
