### PR TITLE
Automated fuzzing

### LINKED ISSUE #1737: Suggestion: Continuous Fuzzing
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

### PR DESCRIPTION
**Pull request by bookmoons**
## Which problem is this PR solving?

Closes #1737.

## Short description of the changes

Integrates with [Fuzzit](https://fuzzit.dev/) for automated fuzzing. Proposed in #1737.

Runs fuzz regression tests in CI every push and PR. Runs full length fuzzing on Fuzzit every push. Uses genetic fuzzer [go-fuzz](https://github.com/dvyukov/go-fuzz).

Fuzzing targets are:
* Zipkin deserialization.
* JSON deserialization.
* HTTP requests to an agent.

There's a successful test build here:
https://travis-ci.org/bookmoons/jaeger/builds/583020533

The PR build will fail due to missing an API key. If you'd like to [sign in](https://fuzzit.dev/) to create an account I can add you to the jaeger org. Then setup is like this:
* In Fuzzit settings grab an API key.
* In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.

### CODE REVIEW

**Comment by bookmoons** [comment]
I get intermittent build failures, even without my changes. Is that a known issue? For the test build I disabled the normal build jobs.

**Comment by jpkrohling** [comment]
> If you'd like to sign in to create an account I can add you to the jaeger org

I'm there, just signed up using my GitHub account.

**Comment by jpkrohling** [comment]
> I get intermittent build failures, even without my changes. Is that a known issue? For the test build I disabled the normal build jobs.

Apparently, everything is working fine except the fuzz step, which is failing because of the missing API Key:
image

And here's what I see [in the logs](https://travis-ci.org/jaegertracing/jaeger/jobs/583029394#L571):

> 2019/09/10 07:32:46 Please set env variable FUZZIT_API_KEY or pass --api-key. API Key for you account: https://app.fuzzit.dev/settings

**Comment by bookmoons** [comment]
Added you to the org.

https://app.fuzzit.dev/orgs/jaeger/settings

> Apparently, everything is working fine except the fuzz step, which is failing because of the missing API Key:

OK, good deal. Maybe there's something different about our Travis accounts.

There are some failures without my changes. Different jobs fail on different runs.

https://travis-ci.org/bookmoons/jaeger/builds/582482304
https://travis-ci.org/bookmoons/jaeger/builds/582478457

**Comment by bookmoons** [comment]
Pushed an upgrade to the Fuzzit client that gets regression tests running in PRs without an API key.

**Comment by jpkrohling** [comment]
Sorry for taking so long to look into this... Just wanted to confirm that this is what we should be seeing in Fuzzit:

image

**Comment by bookmoons** [comment]
Pushed an exploratory change to this, that tries to duplicate the fixture from tests. I'm going to let the fuzz job run and see if it still leaks.

**Comment by jpkrohling** [comment]
Did it work? I see two jobs still in progress, started yesterday "9/30/2019, 11:14:17 AM".

By the way, in case you work at the company behind fuzzit, here's a request for enhancement: add the timezone to the date.

**Comment by bookmoons** [comment]
Yeah, that bit did work. Pushing an upgrade to the latest Fuzzit client which also seemed to help.

But the zipkin fuzzer is hitting a different issue. I've been thinking the right way to handle it. Maybe the Fuzzit reporting could be better but it seems to be a leak in the code. I'm attaching a crashing input from a local run. I bet fixing the leak would stop it from hitting Failed, until that can be improved in Fuzzit.

```fatal error: runtime: out of memory```

[crashers.zip](https://github.com/jaegertracing/jaeger/files/3677319/crashers.zip)

I'll pass along the time zone request to the Fuzzit team.

**Comment by bookmoons** [comment]
In that archive the unsuffixed file is the crashing input.

**Comment by bookmoons** [comment]
Fuzzit say they like the time zone idea and they'll get on it.

**Comment by bookmoons** [comment]
Maybe the zipkin issue isn't a blocker. Getting the other 2 running is probably valuable, and it could be handled over time.

**Comment by bookmoons** [comment]
I see this crossdock failure without my changes. Demonstration here:
https://travis-ci.org/bookmoons/jaeger/builds/592400338

There's a successful run of the fuzzing stages by skipping crossdock:
https://travis-ci.org/bookmoons/jaeger/builds/592392023

---

Proposed approach to the issue: get jaeger set up with the 3 fuzzers. `agent` and `deserialize-json` are in good shape. `deserialize-zipkin` is nonoptimal but it does run for a while and has a chance to catch crashes. A later effort can improve the zipkin fuzzer.

That puts the available fuzzers to use to get some bug discovery happening for you.

**Comment by jpkrohling** [comment]
I'm OK in starting small and expanding over time. I have to admit that I'm in no position to expand it, though.

**Comment by bookmoons** [comment]
OK, I think those fuzzers are a good start.

This build failure seems to happen intermittently in the build history. Here are 2 recent builds that show it:
https://travis-ci.org/jaegertracing/jaeger/jobs/586437160
https://travis-ci.org/jaegertracing/jaeger/jobs/584330120

```✗ [endtoend] test_driver→ (services=go) ⇒ Fail: could not retrieve traces from query service```

If that's an expected failure I think this is ready for final review. If it's approved the last thing to do is transfer the API key from Fuzzit to Travis. Be sure to pull it from the jaeger org, there's a dropdown at the top, it's easy to land in your user org which has different keys.

**Comment by jpkrohling** [comment]
Is it sufficient to export the env var `FUZZIT_API_KEY`? Is that the one the binary looks for?

**Comment by bookmoons** [comment]
Yeah that's the one. If you put in Travis settings for the repo then the client can use it.

**Comment by jpkrohling** [comment]
It's there now.  The crossdock job keeps failing, perhaps more often than it normally does. I'm starting it again once more. In the meantime: would you like to rebase your branch, or would you prefer me to do it via GitHub UI?

**Comment by jpkrohling** [comment]
@jaegertracing/jaeger-maintainers, this change might affect the stability of the CI jobs. Keep an eye for increased intermittent test failures or failures in the `fuzz` CI job.

**Comment by bookmoons** [comment]
Thanks for merging!

**Pull request merged**
