### PR TITLE
Adding SBOM file and pointer in README.md

### PR DESCRIPTION
**Pull request by jkowall**
Signed-off-by: jkowall <jkowall@kowall.net>

## Which problem is this PR solving?
Resolves the lack of SBOM for Jaeger project

## Short description of the changes
Added .json and pointer. This is generated from syft via the all-in-one docker image 
`syft jaegertracing/all-in-one:1.38 -o json > jaeger-sbom.json`

This will help us fix gaps in our security setup per : https://clomonitor.io/projects/cncf/jaeger#jaeger_security

### CODE REVIEW

**Comment by yurishkuro** [comment]
Is this a good practice to publish a one-off SBOM? I would think it needs to be produced during the build process and maybe included in the github release page.

**Comment by jkowall** [comment]
> Is this a good practice to publish a one-off SBOM? I would think it needs to be produced during the build process and maybe included in the github release page.

This is what Pixie is doing, but other projects have integrated the syft gh action into their release flow. I was going to do that, but this seemed like an easy fix. An example of a syft integration for a CNCF project is here: https://github.com/artifacthub/hub/blob/master/.github/workflows/release.yml 

I am not confident how to test the build process really even after reading the docs, if I can do that on a fork, so I opted for the easy path for the SBOM.

**Comment by mmorel-35** [comment]
Have you already thought to use https://github.com/CycloneDX/gh-gomod-generate-sbom ?
Gosec is already using it, if you want an example, please have a look here : https://github.com/securego/gosec/blob/6cd9e6289db3ae9a81f9d0a4f6f7aacb4bca4410/.github/workflows/release.yml#L39-L43

**Comment by yurishkuro** [comment]
@jkowall the full build of binaries is just running a shell script, it can be tested locally. Uploading the file to release is probably harder to test from a fork, but that's done by a GH action and you just need to add the glob for the file (see .github/workflows/ci-release.yml)

**Comment by mmorel-35** [comment]
If you want to take a look, I tried it here : https://github.com/mmorel-35/jaeger/actions/runs/3207214623

**Comment by jkowall** [comment]
@mmorel-35 Feel free to contribute you know the GH actions better than I do :)

**Comment by mmorel-35** [comment]
Hi @jkowall  !
I did it here #3956

**Comment by jkowall** [comment]
This PR should fix up several items around https://github.com/jaegertracing/jaeger/issues/3943

**Pull request closed without merging**
