### PR TITLE
Fix Chinese quotes

### PR DESCRIPTION
**Pull request by zhangdb-git**
Fix Chinese quotes.

### CODE REVIEW

**Comment by albertteoh** [comment]
@zhangdb-git  please sign your commit: https://github.com/jaegertracing/jaeger/pull/3098/checks?check_run_id=2874401988

**Comment by zhangdb-git** [comment]
@joe-elliott Could you review my PR ?

**Review by joe-elliott — APPROVED** [review]

**Comment by joe-elliott** [comment]
This is easy to approve, but @albertteoh is correct. You need to sign your commit.

The link from the failed DCO job explains it:
https://github.com/jaegertracing/jaeger/pull/3098/checks?check_run_id=2874401988

**Comment by jpkrohling** [comment]
@zhangdb-git, are you still interested in this PR?

**Pull request closed without merging**
