### PR TITLE
[jaeger-v2] Align Kafka Storage Config With OTEL

### LINKED ISSUE #6002: [jaeger-v2] Align Kafka Config With OTEL
### Requirement

In this issue, we want to align the configuration for kafka with OTEL (part of https://github.com/jaegertracing/jaeger/issues/5229)

### Tasks / outcomes

- [ ] All config fields are tagged with mapstructure such that they can be addressable from YAML via "good" names
- [ ] Configs implement Validate()
- [ ] Configs via YAML support the same defaults as in jaeger-v1
- [ ] Configs reuse standard elements of OTEL configs whenever possible, e.g. TLS, clientcfg, etc.
- [ ] Configuration looks "logical" and properly grouped, not flattened with long weird names
- [ ] We create a migration guide document with a table that lists v1 CLI flags and the corresponding v2 config fields

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Resolves #6002

## Description of the changes
- 

## How was this change tested?
- 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
in v2 we are using upstream Kafka exporter and receiver, I don't think there's anything that we need to fix.

**Comment by mahadzaryab1** [comment]
> in v2 we are using upstream Kafka exporter and receiver, I don't think there's anything that we need to fix.

Ah I see. I didn't realize that these configs are only used by v1. Is there anything that needs to be done for Kafka as there is a checkbox for it on https://github.com/jaegertracing/jaeger/issues/5229? If not, I can close out this PR and the corresponding issue.

**Comment by yurishkuro** [comment]
no, nothing to do for Kafka in v2

**Comment by mahadzaryab1** [comment]
Closed as per discussion above

**Pull request closed without merging**
