### PR TITLE
WIP: Change ES tag schema to support tag search in Kibana

### LINKED ISSUE #906: Span format is not well suited for ES
Jaeger spans, when put in elasticsearch, have the following structure:

```
{
  "_index": "jaeger-span-2018-07-02",
  "_type": "span",
  "_id": "a3RsXWQBjGb8h888uVuL",
  "_version": 1,
  "_score": null,
  "_source": {
    "traceID": "f229796cda43df60",
    "spanID": "274c0d9d4fc76848",
    "parentSpanID": "f229796cda43df60",
    "flags": 1,
    "operationName": "/",
    "references": [
      {
        "refType": "CHILD_OF",
        "traceID": "f229796cda43df60",
        "spanID": "f229796cda43df60"
      }
    ],
    "startTime": 1530575763255726,
    "duration": 1798,
    "tags": [
      {
        "key": "component",
        "type": "string",
        "value": "nginx"
      },
      {
        "key": "nginx.worker_pid",
        "type": "string",
        "value": "10767"
      },
      {
        "key": "peer.address",
        "type": "string",
        "value": "10.244.4.100:37542"
      },
      {
        "key": "http.method",
        "type": "string",
        "value": "POST"
      },
      {
        "key": "http.url",
        "type": "string",
        "value": "YYY"
      },
      {
        "key": "http.host",
        "type": "string",
        "value": "XXX"
      },
      {
        "key": "http.status_code",
        "type": "int64",
        "value": "204"
      },
      {
        "key": "http.status_line",
        "type": "string",
        "value": "204 No Content"
      }
    ],
    "logs": [],
    "processID": "",
    "process": {
      "serviceName": "ingress-controller",
      "tags": [
        {
          "key": "jaeger.version",
          "type": "string",
          "value": "C++-0.2.0"
        },
        {
          "key": "hostname",
          "type": "string",
          "value": "vega"
        },
        {
          "key": "ip",
          "type": "string",
          "value": "127.0.0.1"
        }
      ]
    },
    "warnings": null,
    "startTimeMillis": 1530575763255
  },
  "fields": {
    "startTimeMillis": [
      "2018-07-02T23:56:03.255Z"
    ]
  },
  "sort": [
    1530575763255
  ]
}
```

Notice the arrays here. The problem is that we were actually thinking about completely replacing debug logs with debug traces, but because everything is in arrays we can't index these spans in ES and thus cant really reliably search them. Jaeger is nice, but ES has much richer search capabilities and it would be just great if we could treat spans as regular structured documents we can put in ES and index properly.

Is there any plans to support this use case?

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #906 

Example tag mapping
```json
tags: {
  "http:method": {
     "value": "GET",
     "type": "string"
  }
}
```

With this mapping default ES configuration stores ~183 unique tag keys - see also https://github.com/jaegertracing/jaeger/pull/980#issuecomment-412579982

### CODE REVIEW

**Comment by yurishkuro** [comment]
what about backwards compatibility with the data people already have stored in ES?

**Comment by pavolloffay** [comment]
> what about backwards compatibility with the data people already have stored in ES?

**Comment by pavolloffay** [comment]
> what about backwards compatibility with the data people already have stored in ES?

I haven't been thinking about it yet. We could provide a migration to new model or support query for old model.

**Comment by pavolloffay** [comment]
Performance results https://github.com/pavolloffay/jaeger-perf-tests,  300k spans different limit parameter for jaeger-query

`QUERY_FROM=jaeger-query JAEGER_QUERY_ASYNC=true NUMBER_OF_SPANS=50000 NUM_OF_TRACERS=6 JAEGER_QUERY_LIMIT=50000 mvn clean package exec:java`

limit 50000
limit 1500 https://pastebin.com/nX0SQQXP

Query time of
`http://localhost:16686/api/traces?service=perf-test-thread-0&limit=50000&lookback=1h&tags={"fooo.bar*?%http.d6cconald":"hehuhoh$?ij","fooo.ba2sar":"true","fooo.ba4342r":"1","fooo.bar1":"fobarhax*+??","fooo.bar*?%http.do**2nald":"goobarRAXbaz","fooo.bar*?%http.don(a44ld":"goobarRAXbaz","fooo.ba24r*?%":"hehe"}`

limit 50000:
limit 1500: mean = 681.32 milliseconds
limit 20: mean = 41.09 milliseconds

The number of tags does not seem to affect query time

**Comment by Monnoroch** [comment]
I think #980 is a better solution. Types are just noise, given that ES already infers them. If you have untyped tags this is not true any more, but it is a bad practice and you always have the option of typing them as strings as an ad-hoc fix.

**Comment by pavolloffay** [comment]
Most important piece of my proposal is that only *specified tags would be stored as direct object. Other tags would still be stored as nested object like it is right now.

* standard OpenTracing tags https://github.com/opentracing/specification/blob/master/semantic_conventions.yaml#L9 and configured tags.

**Pull request closed without merging**
