### PR TITLE
Update to Sarama 1.20.0

### PR DESCRIPTION
**Pull request by marqc**
## Which problem is this PR solving?

Issue #1247  

## Short description of the changes

Upgrade shopify/Sarama dependency.
I tested ingester app against Kafka server 2.0.1 with log.message.format.version=2.0-IV1

### CODE REVIEW

**Comment by marqc** [comment]
@vprithvi how did your internal test go?

**Comment by vprithvi** [comment]
@marqc haven't yet tried it out because of code freeze. Hoping to have a response by next week.

**Comment by objectiser** [comment]
@marqc Could you rebase as the branch is now out of date?

@vprithvi Any more news on the internal tests? Would be good if we can get this in for 1.9.

**Comment by marqc** [comment]
@objectiser Changes merges with master without conflicts. This branch will always be out-of-date with master because there are multiple commits pushed to master everyday.

**Comment by yurishkuro** [comment]
Last I check Prithvi was about to deploy one instance with the upgraded sarama, I'll check with him tomorrow

**Comment by vprithvi** [comment]
We deployed and saw no significant changes in CPU/Memory/goroutines/etc. Nothing scientific, but good enough to merge! Apologies for the delays.

**Pull request merged**
