### PR TITLE
Add CodeQL Analysis workflow

### PR DESCRIPTION
**Pull request by jhutchings1**
Adds a GitHub Actions workflow that runs CodeQL on every push, and on a daily schedule.

Code scanning looks for vulnerabilities, such as XSS, SQL injection, etc., in your code. If it finds any new vulnerabilities it surfaces them in the PR as check annotations, and blocks the build until they’re fixed or marked as false positives. If it finds any on the repo’s default branch it displays them in the [security tab](../security/code-scanning).

For now you also need to be feature flagged individually to see results in the security tab (as well as having write permission on this repo) - if you drop an email to jhutchings1@github.com I can get anyone you need added. 

Finally, this is an early access program that has not been released yet, so please don't share before May 6th when we’re unveiling it at GitHub Satellite.

Cc: @greysteil

### CODE REVIEW

**Comment by objectiser** [comment]
@jhutchings1 would you be able to sign the commit?

**Comment by yurishkuro** [comment]
@jhutchings1 is lgtm.com related to CodeQL? Somehow I ended up on that website when clicking from CodeQL announcement email.

**Comment by jhutchings1** [comment]
Yes, lgtm.com also uses the CodeQL technology that GitHub acquired from
Semmle last year. Code scanning is a new version replatformed on GitHub.
-- 
Justin Hutchings | Senior Product Manager | GitHub - Security |
<https://www.github.com/jhutchings1>
<https://www.linkedin.com/in/hutchingsjustin/>
<https://www.linkedin.com/in/hutchingsjustin/>

**Comment by yurishkuro** [comment]
Then perhaps I'm missing something. This shows several warnings: https://lgtm.com/projects/g/jaegertracing/jaeger-client-go?mode=list. But when I enabled similar GH Action as in this PR and it ran there (https://github.com/jaegertracing/jaeger-client-go/actions/runs/98756561), it shows status as green.

**Comment by jhutchings1** [comment]
We tightened up the default set of queries for code scanning to only look for Security issues. You can add more queries in the configuration if you like though.

**Pull request merged**
