### PR TITLE
Change index prefix from : to -

### LINKED ISSUE #1238: es.index-prefix should not include `:`
## es.index-prefix should not include `:`

It would be better if the index-prefix did not include `:`, is there an explicit reason this is included? It actually prevents uniformity with our other elasticsearch indices. We have elasticsearch curator code that pattern matches, and the colon makes this more tedious. 

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Either exclude the `:` in the es.index-prefix or make it optional.

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #1238 

Spark dependencies: https://github.com/jaegertracing/spark-dependencies/pull/52

The readers will still read from indices containing prefix "prefix:"
to keep backward compability.

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by pavolloffay** [comment]
cc @jaegertracing/elasticsearch

**Comment by objectiser** [comment]
@pavolloffay I think Yuri has a point about the index prefix should be the full prefix, without adding an extra separator. Maybe we could add a temporary command line flag, e.g. `es-old-index-flag` where the user could specify the old index name (with or without the `:`) separator? This way, the additional indexes are only included as long as the user needs the old indices included.

**Comment by pavolloffay** [comment]
@yurishkuro I had exactly the same comment in https://github.com/jaegertracing/jaeger/issues/1238#issuecomment-444809590. I am keen on this approach adding the separator in other projects is annoying. However this will mean a potential breaking change. If we go with plain prefix without separator can we release as 1.9? We want to release on Monday so please comment.

What I have done at the moment does not require any migration. The only thing to keep an eye on is to use the older version of `es-index-cleaner` to delete the old indices.

If we go with the plain prefix - without adding a separator it will require a migration (If users want to migrate to `-`, otherwise then can add `:` to prefix). Users will have to create aliases e.g. `prod-jaeger-span-2019-01-17` pointing to `prod:jaeger-span-2019-01-17` for all indices they would like to read from - depending on `--es.max-span-age` (default 3 days/indices).

> Maybe we could add a temporary command line flag, e.g. es-old-index-prefix where the user could specify the old index name (with or without the :) separator?

* It can be done with the plain prefix without separator users will add `:` at the end of the prefix. The flag would not be enabled by default so it requires some configuration one way or another.

**Comment by yurishkuro** [comment]
Another option is to keep this hardcoded separator for now, do a release without serious migration requirements, and then in the next release remove the separator. Next release will be breaking for configuration, but with easy migration since by then old index names would hopefully TTL-out

**Comment by pavolloffay** [comment]
@yurishkuro I am not sure if I am following you. Could you please be specific about what you are proposing?  

> Another option is to keep this hardcoded separator for now,

So noop in this release? Or keep the current state of this PR?

> Next release will be breaking for configuration, but with easy migration since by then old index names would hopefully TTL-out

So the next release remove the separator and require it to be added by users? 
TTL-out depends on how users are configuring `max-span-age` and if they migrate version by version which might not be always true.

**Pull request merged**
