### PR TITLE
Fix TLS grpc connection on windows

### LINKED ISSUE #2550: jaeger-agent --reporter.grpc.tls.enabled=true fails on windows
**Describe the bug**
Due to https://github.com/golang/go/issues/16736, the jaeger-agent is unable to setup a connection to a tls grpc reporter endpoint on windows.

Error message:
```
{"level":"fatal","ts":1602401908.4807255,"caller":"command-line-arguments/main.go:67","msg":"Could not create collector proxy","error":"failed to load TLS config: failed to load CA CertPool: failed to load SystemCertPool: crypto/x509: system root pool is not available on Windows","stacktrace":"main.main.func1\n\tcommand-line-arguments/main.go:67\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v0.0.3/command.go:762\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v0.0.3/command.go:852\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v0.0.3/command.go:800\nmain.main\n\tcommand-line-arguments/main.go:102\nruntime.main\n\truntime/proc.go:204"}
```

**To Reproduce**
1. run jaeger-agent.exe with --reporter.grpc.tls.enabled=true

**Expected behavior**
It works

**Version (please complete the following information):**
 - OS: Windows
 - Jaeger version: v1.20.0

**Additional context**
https://github.com/golang/go/issues/16736
https://github.com/sensu/sensu-go/pull/4018

### PR DESCRIPTION
**Pull request by wscheele**
Resolves #2550
Borrows workaround from Sensu:
https://github.com/sensu/sensu-go/pull/4018

Signed-off-by: Wouter Scheele <wscheele@gmail.com>

### CODE REVIEW

**Comment by jpkrohling** [comment]
CI restarted.

**Review by jpkrohling — COMMENTED** [review]
Is it possible to test this at all?

**Comment by wscheele** [comment]
For what it's worth, I have deployed, and am using, the branch built windows agent; and it runs happily and reports to tls enabled collector. Without the workaround it just immediately bails out. running the v1.20.1 windows build with --reporter.grpc.tls.enabled=true (pointing to a tls endpoint) should reproduce it easily.

I noticed I introduced some lint and test failures in the build, but am not too familiar with Go in general, and not at all familiar with this codebase and test setup specifically. I would be happy to enrich the PR with further changes to get a green build, but would appreciate some pointers in that case.

**Comment by jpkrohling** [comment]
> I noticed I introduced some lint and test failures in the build, but am not too familiar with Go in general, and not at all familiar with this codebase and test setup specifically. I would be happy to enrich the PR with further changes to get a green build, but would appreciate some pointers in that case.

The problem is that the Linux version of syscall doesn't have a `CertOpenSystemStore` method, for instance. The typical way of handling those cases in Go is to have the same function in different sources, each with a specific platform build tag. In the sensu-go PR you linked, you can see that they have two sources for the "fetcher": `asset/fetcher_unix.go` and `asset/fetcher_windows.go`. The first line in the Unix version looks like this:

```go
 // +build !windows
```

And the first line for the Windows version:

```go
 // +build windows
```

You'll need to do the same for this PR here. You can use the same approach for tests: create a Windows-specific test in a separate source file, requiring ` // +build windows`. I don't think we are testing things in Windows at all, though.

**Comment by pere3** [comment]
Currently facing the same issue, so we are very eager for this merge - @wscheele would you kindly fix tests issues or you about to abandon it?

**Comment by yurishkuro** [comment]
I think this has been fixed by #2756

**Comment by roederja2** [comment]
I'm running version 1.22.0 but I still get `failed to load TLS config: failed to load CA CertPool: failed to load SystemCertPool: crypto/x509: system root pool is not available on Window`. Specifying --reporter.grpc.tls.ca with an appropriate .pem file fixes it

**Comment by Sepisak** [comment]
I am now running jaeger-all-in-one.exe version 1.32.0 under Windows 10 and still get `could not start gRPC collector failed to load CA CertPool: failed to load SystemCertPool: crypto/x509: system root pool is not available on Windows` when I run commad `jaeger-all-in-one --collector.zipkin.host-port=:9411 --collector.grpc.tls.enabled=true`

**Pull request closed without merging**
