### PR TITLE
Use math.MaxUint64 instead of 0xffffffffffffffff

### PR DESCRIPTION
**Pull request by majorteach**
## Which problem is this PR solving?

- Use the variables included in the go standard library to make the code clearer

## Description of the changes
- Math MaxUint64 is a constant currently defined in the go standard library and can be used directly without having to define it repeatedly

## How was this change tested?
- no need

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by james-ryans** [comment]
Hmm.. is there any explanation why is this PR needed? Maybe adding the "Which problem is this PR solving?" will clarify things, because I can't see what is this PR trying to solve. 🤔

**Comment by majorteach** [comment]
> Hmm.. is there any explanation why is this PR needed? Maybe adding the "Which problem is this PR solving?" will clarify things, because I can't see what is this PR trying to solve. 🤔

Thanks. Modified

**Review by yurishkuro — APPROVED** [review]

**Comment by james-ryans** [comment]
@majorteach there is a Github CI check failing, it is because your PR is opened from the main branch of your fork. As we're not allowed to directly push commits to `main` branch, please create another branch and open a new PR.

**Comment by majorteach** [comment]
> there is a Github CI check failing, it is because your PR is opened from the main branch of your fork. As we're not allowed to directly push commits to `main` branch, please create another branch and open a new PR.

Thanks!

**Comment by majorteach** [comment]
> @majorteach there is a Github CI check failing, it is because your PR is opened from the main branch of your fork. As we're not allowed to directly push commits to `main` branch, please create another branch and open a new PR.

The new PR https://github.com/jaegertracing/jaeger/pull/5295

I checkout from main and use another branch name.

Thanks

**Pull request closed without merging**
