### PR TITLE
use Shopify/sarama 1.26.4

### PR DESCRIPTION
**Pull request by prymitive**
## Which problem is this PR solving?

Sarama 1.22.x that's currently used supports Kafka up to 2.2.0, so when using more recent Kafka release not all features will be used. Additionally when there's a mismatch between supported protocol version Kafka might need to convert messages from what's supported in the client and what broker supports, which adds overhead.

https://github.com/Shopify/sarama/blob/master/CHANGELOG.md

## Short description of the changes

This change switches to latest Shopify/sarama client to add support for latest Kafka releases.

### CODE REVIEW

**Comment by yurishkuro** [comment]
Kafka integration test failed:
```
=== RUN   TestKafkaStorage/GetTrace
    integration.go:89: Waiting for storage backend to update documents, iteration 1 out of 30
    integration.go:184: trace not found
    integration.go:89: Waiting for storage backend to update documents, iteration 2 out of 30
    integration.go:184: trace not found
panic: non-positive interval for NewTicker
goroutine 52 [running]:
time.NewTicker(0x0, 0xc00006260c)
	/home/travis/.gimme/versions/go1.14.6.linux.amd64/src/time/tick.go:23 +0x225
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc000120000, 0xc000048d20)
	/home/travis/gopath/pkg/mod/github.com/bsm/sarama-cluster@v2.1.13+incompatible/consumer.go:458 +0x93
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc00000e700, 0xc0000505b0)
	/home/travis/gopath/pkg/mod/github.com/bsm/sarama-cluster@v2.1.13+incompatible/util.go:73 +0xe0
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
	/home/travis/gopath/pkg/mod/github.com/bsm/sarama-cluster@v2.1.13+incompatible/util.go:69 +0x74
FAIL	github.com/jaegertracing/jaeger/plugin/storage/integration	3.413s
FAIL
```

**Comment by prymitive** [comment]
Looks like <=0 value is passed to https://github.com/bsm/sarama-cluster/blob/v2.1.13/consumer.go#L458
need to find out what sets it

**Comment by prymitive** [comment]
Added a potential workaround, but looks like a replacement for bsm/sarama-cluster would be useful

**Comment by yurishkuro** [comment]
@prymitive was there another issue ticket that this PR resolved?

**Comment by prymitive** [comment]
No ticket
all I wanted was to upgrade Sarama so our Kafka cluster doesn’t have to covert messages all the time

**Pull request merged**
