### PR TITLE
fix http response header (#2924)

### LINKED ISSUE #2924: The response ContentType of  HealthCheck.Handler is not application/json
**Describe the bug**
The response ContentType of  HealthCheck.Handler is not application/json

**To Reproduce**
1. run an agent server
2. run ```curl -s -D - http://target-agent-server:14271/```
3. check the ContentType of http response header

**Expected behavior**
The response ContentType should be *application/json*

**Screenshots**
image

**Version (please complete the following information):**
 - OS: osx
 - Jaeger version: 1.22.0
 - Deployment: Docker

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

### PR DESCRIPTION
**Pull request by logeable**
## Which problem is this PR solving?
- Resolve #2924

## Short description of the changes
-

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]
Thanks!

In the future, please add `Resolve #1234` to the description to link & close the respective ticket.

**Comment by yurishkuro** [comment]
@Ashmita152 this is an interesting example where many GH actions fail because the source branch of the fork is also master, and it's confusing the scripts into thinking they need to do Docker release as if it was on real master.

**Comment by yurishkuro** [comment]
@logeable do you mind re-creating this PR from a named branch in your fork?  In general, I do not recommend doing PRs from master even in your own fork, it's best to keep master in sync with upstream.

**Comment by logeable** [comment]
> Thanks!
> 
> In the future, please add `Resolve #1234` to the description to link & close the respective ticket.

Thanks for reminding.

**Comment by logeable** [comment]
> @logeable do you mind re-creating this PR from a named branch in your fork? In general, I do not recommend doing PRs from master even in your own fork, it's best to keep master in sync with upstream.

Ok, I'll create a new pr.

**Pull request closed without merging**
