### PR TITLE
Add go routine leak check in `./internal/tracegen/`

### PR DESCRIPTION
**Pull request by Pushkarm029**
## Which problem is this PR solving?
- part of #5006 

## Description of the changes
- Added go routine leak check in `./internal/tracegen/`

## How was this change tested?
- `make test`

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
goleak check is pointless unless there are unit tests in the package

**Comment by Pushkarm029** [comment]
Ok, I am adding unit tests.

**Comment by Pushkarm029** [comment]
but, unit tests for this package `./internal/tracegen` are already added in #5119

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
thanks

**Pull request merged**
