### PR TITLE
Bump ES docker version

### LINKED ISSUE #1108: ES integration test is flakey
## Requirement - what kind of business use case are you trying to solve?
Have tests be indicative of real problems

## Problem - what in Jaeger blocks you from solving the requirement?
```
=== RUN   TestElasticsearchStorage/GetDependencies
--- FAIL: TestElasticsearchStorage (89.25s)
    --- FAIL: TestElasticsearchStorage/GetTrace (4.21s)
        integration_test.go:100: Waiting for storage backend to update documents, iteration 1 out of 30
. to update documents, iteration 30 out of 30
        integration_test.go:181: No trace with that ID found
        integration_test.go:181: No trace with that ID found
        <autogenerated>:1: 
            	Error Trace:	integration_test.go:185
            	            				integration_test.go:378
            	Error:      	Should be true
            	Test:       	TestElasticsearchStorage/GetTrace
        <autogenerated>:1: 
            	Error Trace:	domain_trace_compare_test.go:53
            	            				integration_test.go:186
            	            				integration_test.go:378
            	Error:      	Expected value not to be nil.
            	Test:       	TestElasticsearchStorage/GetTrace
    --- FAIL: TestElasticsearchStorage/GetLargeSpans (78.75s)
        integration_test.go:132: Testing Large Trace over 10K ...
        integration_test.go:100: Waiting for storage backend to update documents, iteration 1 out of 30
.
        integration_test.go:100: Waiting for storage backend to update documents, iteration 30 out of 30
        <autogenerated>:1: 
            	Error Trace:	integration_test.go:143
            	            				integration_test.go:379
            	Error:      	Should be true
            	Test:       	TestElasticsearchStorage/GetLargeSpans
        <autogenerated>:1: 
            	Error Trace:	domain_trace_compare_test.go:53
            	            				integration_test.go:144
            	            				integration_test.go:379
            	Error:      	Expected value not to be nil.
            	Test:       	TestElasticsearchStorage/GetLargeSpans
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

TBD

### PR DESCRIPTION
**Pull request by pavolloffay**
An attempt to resolve #1108

### CODE REVIEW

**Comment by pavolloffay** [comment]
The first invocation passed - now restarting.

**Comment by pavolloffay** [comment]
Now the build seems to be stable I have restarted it a couple of times. No single failure so far. Restarting the last time now.

**Comment by pavolloffay** [comment]
@yurishkuro @black-adder could you please restart it later in the US time?

**Comment by vprithvi** [comment]
I think we should merge this and keep the ticket open for some time so if someone experiences build failures, they can comment on the ticket. 
What are the changes in 5.6.12 which seemingly mitigate this problem?

**Comment by pavolloffay** [comment]
+1 I will merge then. I don't know what changes are in 5.6.12. Let's try this and see how it goes.

**Pull request merged**
