### PR TITLE
Enable Lint Rule: import-shadowing

### PR DESCRIPTION
**Pull request by inosmeet**
## Which problem is this PR solving?
- Partial fix for #5506  
## Description of the changes
- Enabled `import-shadowing` in revive linter.
- Changed ambiguous attribute names.

## How was this change tested?
- `make lint` `make test`

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`

### CODE REVIEW

**Comment by inosmeet** [comment]
Hey @yurishkuro!
Can you take a look? thanks!

**Review by yurishkuro — COMMENTED** [review]
I don't mind this linter, but I don't like your choice of replacement names - you are creating very verbose & hard to read names, e.g.:
```diff
-	processor processor.SpanProcessor,
-	consumer consumer.Consumer,
+	spanProcessor processor.SpanProcessor,
+	consumerInstance consumer.Consumer,
```
Go generally encourages the use of shorter names. It doesn't mean you have to go to `p` and `c`, but `proc` and `cons` would still be reasonably readable, much better than `consumerInstance`.

**Review by yurishkuro — APPROVED** [review]
Thanks

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks

**Pull request merged**
