### PR TITLE
Add fake bump to instruments to report metrics in V2 scope

### PR DESCRIPTION
**Pull request by Wise-Wizard**
**Which problem is this PR solving?**

This PR addresses a part of the issue [#5633 ](https://github.com/jaegertracing/jaeger/issues/5633)

**Description of the changes**
This is a PR to achieve Observability Parity in metrics between V1 and V2 components by configuring OTEL Collector to emit desired metrics.
**How was this change tested?**

The changes were tested by running the following command:

```bash
make test
```
```bash
CI actions and compare.py script
```
**Checklist**

- [x] I have read [CONTRIBUTING_GUIDELINES.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md)
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - `for jaeger: make lint test`
  - `for jaeger-ui: yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
I don't think we actually need to merge this, you can just use this during your analysis.

**Comment by Wise-Wizard** [comment]
> I don't think we actually need to merge this, you can just use this during your analysis.

Ok, so what needs to be done next then. Because, I think apart from some of the jaeger_collector metrics satisfactory parity is obtained?

**Comment by yurishkuro** [comment]
You could use this change to generate the comparison documents.

**Comment by Wise-Wizard** [comment]
> You could use this change to generate the comparison documents.
Noted, but like I mentioned in the doc that I was hoping to address the formal user migration guide later on.
My primary focus was to achieve satisfactory parity in metrics and get it approved from you and then move on to tackling healthchecks.

**Pull request closed without merging**
