### PR TITLE
Build binaries for darwin/arm64

### PR DESCRIPTION
**Pull request by jhchabran**
Hello 👋! 

## Which problem is this PR solving?

I noticed that the release binaries do not include darwin/arm64, which is just about adding it to the build scripts. 

## Short description of the changes

I added a target in the Makefile and patched a few other scripts. You can see a successful binary build here https://github.com/jhchabran/jaeger/runs/4216116176?check_suite_focus=true and the release workflow uploads here: https://github.com/jhchabran/jaeger/releases/tag/v1.28.1 

Please tell me if I have missed anything!

### CODE REVIEW

**Comment by albertteoh** [comment]
hi @jhchabran, please [sign your commits](https://github.com/jaegertracing/jaeger/pull/3393/checks?check_run_id=4217187460).

**Comment by jhchabran** [comment]
> hi @jhchabran, please [sign your commits](https://github.com/jaegertracing/jaeger/pull/3393/checks?check_run_id=4217187460).

Oh sorry, It's done now 🙏! (changed my laptop yesterday and forgot to migrate it)

**Comment by albertteoh** [comment]
@jhchabran ah, it looks like you've created the PR off your `master` branch. The CI pipeline doesn't handle this well unfortunately. Please, create the PR off a feature branch on your fork.

**Comment by jhchabran** [comment]
Closing in favour of #3431

**Pull request closed without merging**
