### PR TITLE
[v2] Ensure similar naming for query service metrics

### PR DESCRIPTION
**Pull request by Wise-Wizard**
**Which problem is this PR solving?**

This PR addresses a part of the issue [#5633 ](https://github.com/jaegertracing/jaeger/issues/5633)

**Description of the changes**
This is a Draft PR to achieve Observability Parity between V1 and V2 components by configuring OTEL Collector config files to initialise internal tracer and metrics
**How was this change tested?**

The changes were tested by running the following command:

```bash
make test
```
```bash
CI actions
```
**Checklist**

- [x] I have read [CONTRIBUTING_GUIDELINES.md](https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md)
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - `for jaeger: make lint test`
  - `for jaeger-ui: yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
can you generate the metrics diff and link her (you can upload it to https://gist.github.com/)

**Comment by Wise-Wizard** [comment]
> can you generate the metrics diff and link her (you can upload it to https://gist.github.com/)

https://gist.github.com/Wise-Wizard/d8a9399566e2131dc722b8698a994f95

**Comment by yurishkuro** [comment]
any idea why this one shows in v1 only, while the other two `jaeger_query_xxx` metrics show in `common`? It seems all three would be produced by the same code.
```
        "jaeger_query_requests_total": {
            "operation": "find_trace_ids",
            "result": "err"
        },
```

**Comment by Wise-Wizard** [comment]
> any idea why this one shows in v1 only, while the other two `jaeger_query_xxx` metrics show in `common`? It seems all three would be produced by the same code.
> 
> ```
>         "jaeger_query_requests_total": {
>             "operation": "find_trace_ids",
>             "result": "err"
>         },
> ```

It has the total suffix attached to it for some reason.

**Comment by yurishkuro** [comment]
What about storage metrics emitted by the collector?

**Comment by Wise-Wizard** [comment]
> collector

Which metrics exactly?

**Comment by yurishkuro** [comment]
storage metrics. E.g. we have decorator for SpanReader interface, so when collector saves spans to storage it emits the metrics - we expect to see those from v2 as well.

**Comment by Wise-Wizard** [comment]
> storage metrics. E.g. we have decorator for SpanReader interface, so when collector saves spans to storage it emits the metrics - we expect to see those from v2 as well.

Yes, I wrapped the span reader initialized in Query V2 with the decorator, and those are the jaeger_query_metrics which are seen on :8888

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
