### PR TITLE
[jaeger-v2] Fix e2e storage integration v0.99.0 OTEL col failing

### PR DESCRIPTION
**Pull request by james-ryans**
## Which problem is this PR solving?
- Fix failing CI at all of the v2 storage integration #5397 

> 1. What was the observable problem after upgrade? I.e. how did it manifest?

My assumption was because of OTEL col changed the `ToClientConn` gRPC implementation from DialContext to NewClient here https://github.com/open-telemetry/opentelemetry-collector/pull/9965. Both integration spanWriter and jaegerexporter use OTLP exporter which creates the gRPC connection through the `ToClientConn` above.

> 2. What do you believe the root cause was?

The gRPC connection from OTLP exporter has not yet been successfully settled but the requests have been sent.

From the #5397 PR failing CI at Badger and gRPC storages, Badger failed only at GetServices and GetOperations while gRPC failed at GetServices, GetOperations, and FindTraces.

Since both of them failed at GetServices and GetOperations which is the beginning of the tests, the "spanWriter OTLP exporter" to "OTEL col binary OTLP receiver" connection probably has not yet been successfully settled.

Then, the Badger storage doesn't have any issue with the FindTraces because it cleanup the storage with purge() functionality but the gRPC restarts the remote storage server. With the same assumption, the gRPC connection from OTEL col binary to the remote storage server probably has not been settled yet.

> 3. How does the change fix the root cause?

Retrying the requests solves the issue. Here are my arguments:
- The spanWriter's OTLP exporter retries only at GetServices after the retry config has been enabled, previously requests failed at GetServices and GetOperations.
- The jaegerexporter's OTLP exporter has the same error message "plugin error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp [::1]:17271: connect: connection refused" but success at the 2nd attempt.

## Description of the changes
- Change the spanWriter log level to DEBUG
- Enable retry to integration spanWriter

## How was this change tested?
- Run `make jaeger-v2-storage-integration-test` until it fails since it has a low probability of reproducing the same error

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Is this related to #5418?

**Comment by james-ryans** [comment]
> Is this related to #5418?

No, I haven't figured out why cassandra v2 test is failing.

**Comment by yurishkuro** [comment]
Try to add more details to the description.
  1. What was the observable problem after upgrade? I.e. how did it manifest?
  2. What do you believe the root cause was?
  3. How does the change fix the root cause?

**Comment by james-ryans** [comment]
Do you think adding retry to integration spanWriter and jaegerexporter is good enough? Actually, I wasn't able to break down the cause of this issue since it is hard to replicate locally.

> 1. What was the observable problem after upgrade? I.e. how did it manifest?

My assumption was because of OTEL col changed the `ToClientConn` gRPC implementation from DialContext to NewClient here https://github.com/open-telemetry/opentelemetry-collector/pull/9965. Both integration spanWriter and jaegerexporter use OTLP exporter which creates the gRPC connection through the `ToClientConn` above.

> 2. What do you believe the root cause was?

From the #5397 PR failing CI at Badger and gRPC storages, Badger failed only at GetServices and GetOperations while gRPC failed at GetServices, GetOperations, and FindTraces.

Since both of them failed at GetServices and GetOperations, I'm assuming the "spanWriter OTLP exporter" to "OTEL col binary OTLP receiver" connection has not yet been successfully settled.

Then, the Badger storage doesn't have any issue with the FindTraces because it cleanup the storage with purge() functionality but the gRPC restarts the remote storage server. With the same assumption, the gRPC connection from OTEL col to the remote storage server probably has not been settled yet.

> 3. How does the change fix the root cause?

My intention from creating this PR is actually to try out my hypothesis since I almost can not replicate this (I created a script to loop indefinitely until the test returns other than 0). But turns out by retrying the requests passed the CI test.

**Review by yurishkuro — APPROVED** [review]

**Pull request merged**
