### PR TITLE
Add CLI configurable MaxNumSpans while retrieving spans from ES.

### PR DESCRIPTION
**Pull request by annanay25**
Signed-off-by: Annanay <annanay.a@media.net>

## Which problem is this PR solving?
- Follow up PR for #1202 

## Short description of the changes
- Added a CLI configurable option to limit the number of spans fetched in a single query to the ES backend.

### CODE REVIEW

**Comment by black-adder** [comment]
My only question is are we ok with changing behavior that people are used to? If people upgrade jaeger, they'll automatically be hit with the 10000 limit and not know about it. Perhaps if no limit is set, we don't apply a default limit?

**Comment by annanay25** [comment]
@black-adder; this makes sense. 

However, we could mention the reasons for adopting such a limit in the docs (that it could overwhelm the query-service) and mention that it could be overwritten using the flag in the release notes.

**Comment by yurishkuro** [comment]
please add to the changelog.

is the behavior actually different from before? I thought we already had another 10k limit in the code.

**Comment by yurishkuro** [comment]
This is being reverted in https://github.com/jaegertracing/jaeger/pull/4336

**Pull request merged**
