### PR TITLE
Fix: skipping merge based on PR label

### LINKED ISSUE #4799: [Feature]: (Re)Introduce changelog-related labels and require them for PRs
We already tried this in the past, but there was no enforcement and it didn't take.

* [x] Add a GitHub Action that will verify that a PR has a specific categorization label before it can be merged. We already have a bunch of those labels `changelog:***` labels
  * example of bot: https://github.com/asyncapi/website/pull/2170#issuecomment-1735255198
  * example: https://twitter.com/benasher44/status/1503460237331734528
* [x] Alter the release notes script to validate that all PRs have changelog labels, fail if some don't and print their URLs so that the maintainer can fix them manually. This should ignore dependabot PRs automatically.
* [x] Alter the release notes script to automatically group changes by the labels
* [ ] Apply similar changes to jaeger-ui repo

### PR DESCRIPTION
**Pull request by devidasjadhav**
## Which problem is this PR solving?
Resolves #4799 

## Description of the changes
-  Added github action to skip based on PR label. 

## How was this change tested?
-  tested it on my repository in main branch. which skipped this test.
I have deleted that repo.

## Checklist
- [ x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by devidasjadhav** [comment]
I have fixed first task. i.e.  Add a GitHub Action that will verify that a PR has a specific categorization label before it can be merged. We already have a bunch of those labels changelog:*** labels


I can change label if needed.
Please suggest label. I didn't spot changelog: lable in PR's.

**Comment by yurishkuro** [comment]
* this does not resolve #4799 
* we don't use Do Not Merge label today. I don't see a particular value in it:
  * if PR author does not want PR merged, they can turn it into Draft or add WIP to the title
  * if maintainers don't want PR merged by accident, then can request changes on it via Approvals

**Comment by yurishkuro** [comment]
> Add a GitHub Action that will verify that a PR has a specific categorization label before it can be merged. 

This means the PR must contain a label of the form `/^changelog:.*/`

**Comment by yurishkuro** [comment]
The ticket has been addressed in other PRs.

**Pull request closed without merging**
