### PR TITLE
Docker compose specify restart limit

### PR DESCRIPTION
**Pull request by pavolloffay**
Related to https://github.com/jaegertracing/jaeger/issues/547

### CODE REVIEW

**Comment by pavolloffay** [comment]
The first run passed https://travis-ci.org/jaegertracing/jaeger/builds/304432958. 

We should restart it a couple of times, to be sure whether it's stable

**Comment by yurishkuro** [comment]
what is the default restart count if this value is not given?

10 actually looks rather low to me, since Cassandra can take a while to start.

**Comment by yurishkuro** [comment]
restarting the build

**Comment by pavolloffay** [comment]
the latest restart failed, so this does not fix it.

**Comment by yurishkuro** [comment]
Driver cannot find query service:

`Get http://jaeger-query:16687: dial tcp: lookup jaeger-query on 127.0.0.11:53: no such host`

however it doesn't look like it was restarted 20 times, only 10:

```
$ grep jaeger-query_1 ~/Downloads/log.txt | grep fatal | wc -l
      10
```

It would be nice if we could specify the wait period before the restarts. Cassandra took about 45 seconds to start.

**Comment by pavolloffay** [comment]
The problem is that compose increases delay between restarts so the last delay was higher that wait in `test-driver`.

**Comment by pavolloffay** [comment]
This does not fix the issue, closing in favour of https://github.com/jaegertracing/jaeger/pull/565

**Pull request closed without merging**
