### PR TITLE
Collector-sampling

### LINKED ISSUE #6083: [crossdock] Replace sampling calls to agent with calls to collector
Part of #4739 and #6081

In the crossdock integration tests the test driver tries to connect to the "agent" and test its sampling endpoint response. We need to
  * [x] redirect it to query the sampling endpoint in the collector instead
  * [ ] remove "agent" related code

cc @mahadzaryab1

### PR DESCRIPTION
**Pull request by Garvit-77**
We appreciate your contribution to the Jaeger project! 👋🎉
-->

## Which problem is this PR solving?
- This PR resolves #6083 

## Description of the changes
- Replacing the agent url to the collector url
- changing the endpoints in agent.go as per the endpoints of collector Http sampling

## How was this change tested?
- 

## Checklist
- [ Y ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ Y ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by Garvit-77** [comment]
please let me know any changes 
@yurishkuro @mahadzaryab1

**Comment by inosmeet** [comment]
Hey @Garvit-77!
All the commits must be signed in order to pass the DCO check of the GitHub.

**Comment by yurishkuro** [comment]
Signed commits is not the concern for me here - the PR itself is meaningless, it just deletes two files. I wouldn't open an issue if the problem was with deleting two files.

**Comment by Garvit-77** [comment]
I Absolutely get that and to solve the issue Even i wasn't Deleting two files, rather just changed the endpoints for the function
GetSamplingRate to sample the collector .
I will check what went wrong and raise another pr
Thank You.

**Pull request closed without merging**
