### PR TITLE
Add CORS handling for Zipkin collector service, fixes #703

### LINKED ISSUE #703: Support CORS on Zipkin endpoint
Hi!

I've instrumented a simple Javascript frontend and a web API backend with Zipkin, and this works. I wanted to use Jaeger as a drop-in replacement for Zipkin on port 9411 by stopping Zipkin and starting Jaeger according to the docs:

```
docker run -d -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 -p9411:9411 jaegertracing/all-in-one:latest
```

However, now I get the following error in my Javascript app:

```
Failed to load http://localhost:9411/api/v2/spans: 
Response to preflight request doesn't pass access control check: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:8080' is therefore not allowed access. 
The response had HTTP status code 404. 
If an opaque response serves your needs, set the request's mode to 'no-cors' 
to fetch the resource with CORS disabled.
```

Here's some more details about the failing request:

```
Request URL:http://localhost:9411/api/v2/spans
Request Method:OPTIONS
Status Code:404 Not Found
Remote Address:[::1]:9411
Referrer Policy:no-referrer-when-downgrade
Content-Length:19
Content-Type:text/plain; charset=utf-8
Date:Tue, 20 Feb 2018 17:25:30 GMT
X-Content-Type-Options:nosniff
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,nb;q=0.8,da;q=0.7
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:POST
Connection:keep-alive
Host:localhost:9411
Origin:http://localhost:8080
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
```

I have verified that Jaeger does indeed listen on POST http://localhost:9411/api/v2/spans using Postman.

### PR DESCRIPTION
**Pull request by JonasVerhofste**
Signed-off-by: Jonas Verhofsté <25819942+JonasVerhofste@users.noreply.github.com>

## Which problem is this PR solving?
- Handling of CORS on the Zipkin collector service, issue #703 

## Short description of the changes
- Add and call the CORS handler
- Add variables for allowed origins and headers

### CODE REVIEW

**Comment by JonasVerhofste** [comment]
Not entirely sure where to add tests, if any are needed at all?

**Comment by yurishkuro** [comment]
I don't think this PR needs to include Gopkg.lock changes.

> Not entirely sure where to add tests, if any are needed at all?

What is the expected behavior of the cors handler? Does it reject certain types of requests? That's the type of test I would add.

**Comment by JonasVerhofste** [comment]
>I don't think this PR needs to include Gopkg.lock changes.
Removed.

>What is the expected behavior of the cors handler? Does it reject certain types of requests? That's the type of test I would add.
I'm not sure where to add the tests. Where exactly does the main.go from the collector get tested?

**Comment by yurishkuro** [comment]
Ah, it's ok then. We should have a test for flags, but we don't test main aside from integration tests. Some steps in the build are failing though.

**Comment by JonasVerhofste** [comment]
@yurishkuro Well, the builds didn't fail before (https://travis-ci.org/jaegertracing/jaeger/builds/516424159) and I only removed the lock-file. Some inconsistency in the CI?

**Comment by JonasVerhofste** [comment]
@yurishkuro So, seems like build 2 (proto gen) is failing because I removed `Gopkg.lock`, like you asked. Should I re-add it or is that a fault in the CI?

**Comment by JonasVerhofste** [comment]
ping @yurishkuro

**Comment by yurishkuro** [comment]
Let's see if merging master helps, as this step should not be failing (it doesn't in master)

**Comment by yurishkuro** [comment]
hmm, very odd, lock file comes up as a diff. Need to look into that.

**Comment by yurishkuro** [comment]
ok, fixed it

**Comment by yurishkuro** [comment]
Ah, I see what's going on now. You're adding a new dependency `github.com/rs/cors`, I missed that. In that case, it needs to go to Gopkg.toml, and you DO need to update the lock file.

**Pull request merged**
