### PR TITLE
Bump ui to latest

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by tiffon** [comment]
@pavolloffay, @objectiser Just a heads up, I'm working on a couple of  UI changes to the embed functionality. 

Part of the changes involve renaming the query string parameters. 

I'm OOO for a few days and will likely not be able to finish until early next week.

It's preferable for the current query parameter names to not be released. If the current version is released, please let's have the embed functionality undocumented.

cc @aljesusg, @yurishkuro

**Comment by aljesusg** [comment]
I am going to work in the documentation for the embed functionality, I'll keep the PR until your changes @tiffon

**Comment by pavolloffay** [comment]
I have release 1.8.2 with the embed functionality.

**Comment by pavolloffay** [comment]
The next time I will wait for +1 from all parties before cutting the release.

**Comment by objectiser** [comment]
I think there was an implied understanding that this PR would be released as soon as merged, as it was required by Kiali - however as @tiffon suggests, if it is undocumented and Kiali understands that it will need to update once 1.8.3 (or 1.9.0) is out, then it should be fine.

**Comment by tiffon** [comment]
I appreciate your underatanding!

Wow, fast release! Doh... I made a couple of incorrect assumptions and also didn't manage to finish the changes last night.

Moving forward, I'll operate under the assumption there won't be a buffer between merging a UI PR and cutting a core release.

**Comment by objectiser** [comment]
@tiffon No problem - I think this one was an exceptional circumstance, so hopefully time between UI changes and a core release would not be as quick in future, unless just dealing with patching a fix.

**Pull request merged**
