### PR TITLE
Updates jaeger-idl to current version of OTLP

### PR DESCRIPTION
**Pull request by tanayvaswani**
## Which problem is this PR solving?
- Resolves task 1, 2 from #4648 

## Description of the changes
- Some required changes in `trace.proto`, `resource.proto`, `common.proto` files under their respective directories in **idl/opentelemetry-proto/opentelemetry/proto/** to use the current version of OTLP.
- Executed make proto command for compiling the proto files into `.pb.go`

## How was this change tested?
- Through codegen command in Makefile.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by tanayvaswani** [comment]
I've done some changes in **idl/opentelemetry-proto/opentelemetry/proto/** too, but idk why it isn't getting tracked while pushing the code.

**Comment by yurishkuro** [comment]
We need to make the change in idl repo first and then update the sub module here

**Comment by tanayvaswani** [comment]
> We need to make the change in idl repo first and then update the sub module here

And inside idl repo, changes made in opentelemetry-proto submodule, how can we track that?

**Comment by yurishkuro** [comment]
upgrade that too as submodule -- https://github.com/jaegertracing/jaeger-idl/pull/97

**Comment by yurishkuro** [comment]
that PR failed in the CI, you may want to investigate, as I won't have time

**Comment by tanayvaswani** [comment]
> that PR failed in the CI, you may want to investigate, as I won't have time

Yes 2 tests cases were also failed when I checked after changes in my local environment. The reason behind that I haven't completed the 3rd task, I am working on it.

**Pull request closed without merging**
