### PR TITLE
Memory store limit queries return most recent traces

### LINKED ISSUE #1393: Memory store plugin query results not stable
## Requirement - what kind of business use case are you trying to solve?

I use the memory store plugin for local application development. It's helpful that this store is performant, reliable, has consistent behavior. Scaling and durability are not necessary, of course.

## Problem - what in Jaeger blocks you from solving the requirement?

When I query:
- with "Limit Results" to, say, 10
- the same query with, say, limit 100, would return more than 10 results
- click "Find Traces" more than once

...the results change. Traces appear and disappear from results.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Results should be sorted, then limited. I have a simple PR #1934

## Any open questions to address

None.

### PR DESCRIPTION
**Pull request by jacobmarble**
Fixes #1393

## Which problem is this PR solving?
Memory store query results are not stable.

## Short description of the changes
Sorts memory store query results before limit.

### CODE REVIEW

**Comment by jacobmarble** [comment]
@yurishkuro I think this is a fairly simple PR. Do you mind taking a look?

**Comment by yurishkuro** [comment]
@pavolloffay @objectiser thoughts on this PR?

**Comment by objectiser** [comment]
@yurishkuro I'm in favour of having stable results - even though in-memory should only be used for demo/test purposes, it avoids unnecessary questions about why the results are not consistent.

**Comment by yurishkuro** [comment]
Stable results are good, my main concern was with performance implications, since the complete data set is now being scanned. I supposed we can punt on the performance aspect of this memory storage, if people are really serious about performance, they may want to use Badger (which I hope to merge next week).

**Comment by jpkrohling** [comment]
Agree -- I wouldn't stress too much about the performance of this as this is only about the in-memory storage.

**Comment by JungleYe** [comment]
@jacobmarble  it seems that this merge failed,"This branch is out-of-data with the base branch". so the latest “jaegertracing/all-in-one” is still out of order

**Comment by yurishkuro** [comment]
it looks like there was a race condition in one of the tests

**Comment by JungleYe** [comment]
the results are in order now .thank you @jacobmarble  @yurishkuro

**Pull request merged**
