### PR TITLE
export model and protocol type

### PR DESCRIPTION
**Pull request by oiooj**
The `ProcessorConfiguration` can be exported, but the custom type `model` and `protocol` can not, so it's hard to new a `ProcessorConfiguration` outside the package.

Signed-off-by: kun <oiooj@qq.com>

### CODE REVIEW

**Comment by black-adder** [comment]
May I know the use case for this? Are you planning on writing an entirely new span model?

**Comment by oiooj** [comment]
@black-adder We want merge jaeger agent into our agent, so that we can manage only one agent on all servers.

**Comment by oiooj** [comment]
@black-adder Can this be merged？

**Comment by black-adder** [comment]
Sure, some tests are failing though:

cmd/agent/app/builder_test.go:159:15: undefined: model
cmd/agent/app/builder_test.go:160:15: undefined: protocol

**Comment by oiooj** [comment]
Thank you, I will fix it tomorrow morning

**Comment by oiooj** [comment]
@black-adder updated

**Pull request merged**
